- packages/viewer/src/index.html
The credentials code in the viewer example was outdated. Updating to use the new prop `token`.
https://jira.vertexvis.net/browse/SDK-738
N/A
N/A
N/A
N/A
> [SDK-738] Update example to reflect changes in the viewer

- packages/viewer/.npmrc
- packages/viewer/yarn.lock
Install didn't work for me on first pass. This resolved my issue. 
https://jira.vertexvis.net/browse/SDK-691
- From a clean dir on this project, a yarn install should work for the first time.
N/A
N/A
N/A
> [SDK-691] Fixing Install

- packages/viewer/src/scenes/scene.ts
A fix for immutable builders
https://vertexvis.atlassian.net/browse/SDK-691
See test plan here: https://github.com/Vertexvis/vertex-web-sdk/pull/18
N/A
N/A
N/A
> [SDK-691] pass correct builder

- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
Allows for packages to be published to the public NPM registry.
1. Create a release
2. Merge
3. Packages should show up in the public repo
N/A
N/A
N/A
> [SDK-797] Allow for publishing packages to public repo

- lerna.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
- scripts/publish.sh
Validating that our CI publish scripts work.
> [SDK-797] Release v0.4.1

- README.md
Updates instructions in the README to create a release for the packages in this repo.
https://vertexvis.atlassian.net/browse/SDK-806
> [SDK-806] Update release docs in README

- lerna.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Release graceful reconnect
https://vertexvis.atlassian.net/browse/SDK-798
> Release v0.4.2

- packages/stream-api/src/webSocketClient.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/index.html
There was a bug where reconnecting to a WS would fail.
https://vertexvis.atlassian.net/browse/SDK-829
1. View a model
2. Wait 45 seconds
3. Try to rotate the model
> [SDK-829] Fix reconnection

- lerna.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Release reconnect fix.
https://vertexvis.atlassian.net/browse/SDK-829
> [SDK-829] Release v0.5.1

- lerna.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Releasing fix for disposing an old stream when a new model is loaded.
[SDK-841] dispose of stream when loading a new stream key
[SDK-841]: https://vertexvis.atlassian.net/browse/SDK-841
> Release v0.5.2

- lerna.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Releasing the changes to support platprod by default
> [SDK-850]  Release v0.6.0

- internal/build/LICENSE
- internal/build/package.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer-react/README.md
- packages/viewer-react/package.json
- packages/viewer/README.template.md
- packages/viewer/package.json
- packages/viewer/readme.md
Add or update links in our `package.json` files so they appear correctly in NPM.
https://vertexvis.atlassian.net/browse/SDK-884
> [SDK-884] Update links in package.json files

- packages/viewer/src/components/viewer/viewer.tsx
Clearing error message on unload
Loading a new scene after an error message has occurred should clear the message
N/A
N/A
N/A
> [SDK-953] resetting error message on unload

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/rendering/timing.ts
- packages/viewer/src/types/synchronizedClock.ts
Add logging if we detect a negative send to receive timing.
https://vertexvis.atlassian.net/browse/SDK-1277
> [SDK-1277] Add logging if send to receive timing is negative

- scripts/publish_canary.sh
Run lerna with `npx`.
https://vertexvis.atlassian.net/browse/SDK-876
> [SDK-876] Fix lerna not found error

- lerna.json
https://vertexvis.atlassian.net/browse/SDK-876
> [SDK-876] Whitelist releases from master

- .github/workflows/master.yml
https://vertexvis.atlassian.net/browse/SDK-876
> [SDK-876] Set git user when publishing canary

- README.md
- packages/geometry/README.template.md
- packages/stream-api/README.md
- packages/utils/README.md
- packages/viewer-react/README.md
- packages/viewer/README.template.md
https://vertexvis.atlassian.net/browse/SDK-876
> [SDK-876] Add version badges

- scripts/release.sh
There was a syntax bug in the jq of our release script.
https://vertexvis.atlassian.net/browse/SDK-1388
> [SDK-1388] Fix jq bug in release script

- .github/workflows/master.yml
GA is failing to create a tag and push to the upstream repo. This should fix that.
https://vertexvis.atlassian.net/browse/SDK-1388
> [SDK-1388] Fix tagging of publish release script

- packages/viewer/src/components/viewer/viewer.tsx
Adding some documentation to the viewer's scene property. Using this to test a release.
https://vertexvis.atlassian.net/browse/SDK-1391
> [SDK-1391] Document scene property on the viewer

- lerna.json
- packages/viewer-react/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Testing release script fixes.
https://vertexvis.atlassian.net/browse/SDK-1391
> Release v0.9.21

- packages/viewer/index.html
Uses the base URL from the page to load resources.
https://vertexvis.atlassian.net/browse/SDK-1430
> [SDK-1430] Update URLs in the viewers index.html

- packages/viewer/src/types/interactions.ts
Update to 75ms for interaction delay based on test jam feedback.
https://vertexvis.atlassian.net/browse/SDK-1512
- Test the interaction delay
N/A
N/A
N/A
> [SDK-1512] Update interaction delay

- packages/viewer/src/index.ts
Exporting `TapEventDetails` to the top level of the viewer, as this is a common type.
> [APP-2106] Export Tap Event Details

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/types/crossSectioning.ts
- yarn.lock
Add cross sectioning highlightColor
https://vertexvis.atlassian.net/secure/RapidBoard.jspa?rapidView=65&modal=detail&selectedIssue=API-1845
> [API-1845] Add cross sectioning highlightColor

- yarn.lock
Updates protos to expose item ancestry on hit results.
https://vertexvis.atlassian.net/browse/API-1840
> [API-1840] Expose item ancestry on hits

- packages/stream-api/package.json
- packages/stream-api/src/streamApi.ts
- yarn.lock
Add getStencilBuffer to stream-api
> [API-1940] Add getStencilBuffer to stream-api

- README.md
- packages/viewer/src/components/scene-tree-row/scene-tree-row.tsx
Add test ids to elements in the scene tree.
https://vertexvis.atlassian.net/browse/ENABLE-1870
Look for test ids
None
None
None
> [ENABLE-1870] Add test ids to scene tree

- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.spec.tsx
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.tsx
- packages/viewer/src/components/viewer-measurements/viewer-measurements.tsx
- packages/viewer/src/components/viewer/viewer.tsx
Fixes a bug where pan wouldn't work if a measurement component was added to the viewer. Also updates the measurement interactions to respond to primary mouse buttons.
https://vertexvis.atlassian.net/browse/API-2010
> [API-2010] Fix bug with pan not working with measurements

- packages/viewer/src/components/scene-tree/lib/__tests__/controller.spec.ts
- packages/viewer/src/components/scene-tree/lib/controller.ts
This should fix issues where the scene tree becomes unresponsive after some period of time. This was happening because we would not use the latest JWT from the viewer, and the tree could potentially be destroyed after 5 minutes. The later is addressed by reconnecting after 4 minutes.
https://vertexvis.atlassian.net/browse/API-1986
> [API-1986] Fix scene tree becoming unresponsive after some time

- packages/utils/package.json
- packages/utils/src/__tests__/objects.spec.ts
- packages/utils/src/objects.ts
- packages/viewer/src/components/viewer/viewer.spec.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/scenes/scene.ts
- packages/viewer/src/lib/types/loadableResource.ts
- yarn.lock
Fixes an issue where changing the scene view state via setting `src` wasn't applying the scene view state.
https://vertexvis.atlassian.net/browse/API-1966
> [API-1966] Fix for changing scene view state

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement-components.tsx
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.css
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.spec.tsx
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.tsx
- packages/viewer/src/components/viewer-layer/readme.md
- packages/viewer/src/components/viewer-layer/viewer-layer.tsx
- packages/viewer/src/components/viewer-measurement-line/readme.md
- packages/viewer/src/components/viewer-measurement-line/viewer-measurement-line.css
- packages/viewer/src/components/viewer-measurement-line/viewer-measurement-line.tsx
- packages/viewer/src/components/viewer-toolbar/viewer-toolbar.tsx
- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/index.ts
- packages/viewer/src/lib/__tests__/cursors.spec.ts
- packages/viewer/src/lib/cursors.ts
- packages/viewer/src/lib/dom.ts
This reverts interaction targets to use our previous approach with layering.
https://vertexvis.atlassian.net/browse/API-2033
> [API-2033] Revert approach to interaction targets

- packages/geometry/src/__tests__/plane.test.ts
- packages/geometry/src/__tests__/ray.test.ts
- packages/geometry/src/plane.ts
- packages/geometry/src/ray.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/interactions/__tests__/interactionApi.spec.ts
- packages/viewer/src/lib/interactions/__tests__/mouseInteractionHandler.spec.ts
- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
- packages/viewer/src/lib/interactions/interactionApi.ts
- packages/viewer/src/lib/interactions/mouseInteractions.ts
Adds support for zooming to the current cursor position when zooming via the mouse wheel.
https://vertexvis.atlassian.net/browse/API-1903
> [API-1903] Zoom to cursor interaction

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree/scene-tree.tsx
- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.spec.tsx
- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.tsx
- packages/viewer/src/components/viewer/viewer.tsx
Fixes stencil warnings related to props/state being updated during its render lifecycle.
https://vertexvis.atlassian.net/browse/API-2084
> [API-2084] Fix stencil render warnings

- packages/viewer/src/workers/png-decoder-pool.ts
> [APP-2536] Only run web workers in the browser for nextjs apps

- packages/viewer/src/components/scene-tree/scene-tree.tsx
This prop isn't supported/used. Removing it.
https://vertexvis.atlassian.net/browse/API-2193
> [API-2193] Remove unsupported selection disabled prop from scene tree

- packages/viewer/src/index.ts
The viewport utils are not included in the packages, and these would be useful to me for pins. 😄
> [APP-2621] Including Viewport utils in sdk

- packages/viewer/src/components/viewer-dom-renderer/readme.md
> [APP-2621] Update Readme for viewer-dom-renderer

- packages/viewer/package.json
- yarn.lock
Update version of frame-streaming-protos
> [API-2198] Update version of frame-streaming-protos

- packages/stream-api/package.json
- yarn.lock
Update version of frame-streaming protos in stream-api
> [API-2198] Update version of frame-streaming protos in stream-api

- internal/build/package.json
- package.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer-react/package.json
- packages/viewer/package.json
- typedoc.json
- yarn.lock
https://vertexvis.atlassian.net/browse/API-2270
> [API-2270] Update deps to latest versions

- packages/viewer/src/components/viewer/viewer.tsx
https://vertexvis.atlassian.net/browse/APP-2491
> [APP-2491] clear canvas when viewer unloaded

- packages/viewer-react/rollup.config.js
https://vertexvis.atlassian.net/browse/API-2273
> [API-2273] Remove unused build code from viewer-react

- packages/viewer/src/components/viewer-measurement-details/viewer-measurement-details.spec.tsx
- packages/viewer/src/components/viewer-measurement-details/viewer-measurement-details.tsx
- yarn.lock
Change angle formatting to treat incoming value as radians instead of degrees
> [PLAT-229] Change angle formatting to treat incoming value as radians instead of degrees

- packages/stream-api/package.json
- packages/stream-api/src/streamApi.ts
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
Add ResetView calls to stream-api & viewer Scene
Requires FSS work still.
> [PLAT-438] Add ResetView calls to stream-api & viewer Scene

- packages/viewer/src/components/viewer-measurement-precise/viewer-measurement-precise.tsx
- packages/viewer/src/lib/grpc.ts
- packages/viewer/src/lib/measurement/__tests__/controller.spec.ts
- packages/viewer/src/lib/measurement/controller.ts
Add device-id to grpc metadata for measurement calls when it's available.
> [PLAT-571] add deviceId to measurement metadata

- packages/viewer/src/lib/interactions/__tests__/mouseInteractionHandler.spec.ts
- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
We want the middle mouse button to function like the left mouse button.
Test interacting in the viewer. Make sure that the middle mouse button performs as expected.
Middle mouse button functions like left mouse button.
Interacting with a model in the viewer
None
> [PLAT-472] Middle mouse button functions like left mouse button

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
https://vertexvis.atlassian.net/browse/PLAT-622
> [PLAT-622] Fix layout of scene tree header with multiple columns

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree/errors.tsx
- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/scene-tree/lib/errors.ts
- packages/viewer/src/components/scene-tree/readme.md
- packages/viewer/src/components/scene-tree/scene-tree.css
- packages/viewer/src/components/scene-tree/scene-tree.tsx
- packages/viewer/src/components/viewer-markup/readme.md
- packages/viewer/src/components/viewer-measurements/readme.md
- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/css/button.css
An error connecting to the scene tree would cause the tree to get pushed down. Fixed the layout and also added a retry button.
https://vertexvis.atlassian.net/browse/PLAT-650
> [PLAT-650] Fix layout, improve UX for scene tree errors

- packages/viewer/src/lib/measurement/index.ts
Exposing measurement outcomes so it can be consumed in Connect.
https://vertexvis.atlassian.net/browse/PLAT-753
> [PLAT-753] Expose measurement outcomes

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
@danschultz @jdm717 
Before changes:
After changes:
> [PLAT-792] Update viewport on scroll events

- packages/viewer/src/components/viewer-dom-renderer/renderer3d.tsx
- packages/viewer/src/components/viewer-dom-renderer/viewer-dom-renderer.tsx
Better pin positioning in orthographic mode.
- Test pins in orthographic mode
N/A
N/A
N/A
> [PLAT-271] Compute proper value for orthographic pins

- packages/viewer/src/components/viewer-dom-group/viewer-dom-group.css
- packages/viewer/src/lib/pins/model.ts
Fixing broken dom group css, and not selecting pin by default.
Test view cube
Verify adding a pin does not select it by default
> [PLAT-1099] Remove css changes and dont select pin on addition

- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.tsx
- packages/viewer/src/lib/pins/interactions.ts
Not preventing event propagation and not adding pins on right click
> [PLAT-1099] dont add pin on right click

- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.tsx
Fixing an issue where the partID on the pin gets reset to `''`
> [PLAT-1098] Keep original Part Id

- packages/viewer/src/components/viewer-pin-label/readme.md
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.tsx
- packages/viewer/src/components/viewer-pin-tool/viewer-pin-tool.spec.tsx
- packages/viewer/src/components/viewer-pin-tool/viewer-pin-tool.tsx
- packages/viewer/src/lib/pins/controller.ts
- packages/viewer/src/lib/pins/model.ts
When the pin changes, set the appropriate text
> [PLAT-1108] Set text when changes on the pin

- packages/viewer/src/lib/pins/interactions.ts
Do not calculate from depth buffer, but rely on hit result data.
> [PLAT-1290] Use Hit Result Point

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
These changes introduce a fix to no longer divide by 0.
> [PLAT-1434] Scene Tree Column Layout Fix

- packages/viewer/src/components/scene-tree/scene-tree.tsx
set the error details to undefined when retrying
> [PLAT-1035] Reset error details on a retry

- packages/viewer/src/components/scene-tree/scene-tree.tsx
Once we run the `ensureLayoutDefined` we should also render it in case there are any items returned by the controller that need to be drawn.
> [PLAT-1035] Render after layout defined

- packages/viewer/src/components/scene-tree/scene-tree.tsx
The template element gets replaced, and a render with the updated element never occurred. This should resolve that issue.
> [PLAT-1035] Update Layout after a new layout element gets set in state

- packages/viewer/src/components/viewer-measurement-details/readme.md
- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.tsx
- packages/viewer/src/components/viewer-measurement-line/readme.md
- packages/viewer/src/components/viewer-measurement-overlays/readme.md
Updating the documentation of the measurement detail component.
https://vertexvis.atlassian.net/browse/PLAT-1676
> [PLAT-1676] Update measurement detail docs

- packages/viewer/src/lib/pins/interactions.ts
Clearing the cursor on the interaction handler disposal
> [PLAT-1648] Clear cursor on dispose

- packages/viewer/src/components/scene-tree/lib/controller.ts
These changes should quiet down some of the alerts, and help the alerts be a little more accurate. 
Open and close the scene tree panel. You should not see sit-room alerts for the scene tree connection.
> [PLAT-1772] Clear subscription handshake on unknown failure or component disconnected

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree-table-cell/readme.md
- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.tsx
> [PLAT-1776] Add Selection/Expansion/Visibility Events back in the table cell.

- packages/stream-api/src/time.ts
- packages/utils/package.json
- packages/utils/src/__tests__/uuid.test.ts
- packages/utils/src/uuid.ts
- yarn.lock
Adds a utility to parse MSB and LSB from UUID strings.
https://vertexvis.atlassian.net/browse/PLAT-1808
> [PLAT-1808] Add utility to parse MSB, LSB from UUID strings

- packages/utils/src/__tests__/uuid.test.ts
- packages/utils/src/uuid.ts
Add utility to create UUID string from msb/lsb values.
https://vertexvis.atlassian.net/browse/PLAT-1808
> [PLAT-1808] Add conversion from msb/lsb

- packages/utils/package.json
- packages/utils/src/uuid.ts
- yarn.lock
More efficient conversion.
https://vertexvis.atlassian.net/browse/PLAT-1808
> [PLAT-1808] Refactor UUID.toMsbLsb

- packages/stream-api/src/testing/fixtures/responses.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/interactions/__tests__/flyToPositionKeyInteraction.spec.ts
- packages/viewer/src/lib/interactions/__tests__/interactionApi.spec.ts
- packages/viewer/src/lib/interactions/__tests__/interactionApiOrthographic.spec.ts
- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/scene.ts
- packages/viewer/src/lib/stream/state.ts
- packages/viewer/src/lib/stream/stream.ts
- yarn.lock
Exposes scene ID in the viewer.
https://vertexvis.atlassian.net/browse/PLAT-1876
> [PLAT-1876] Expose scene ID in viewer

- packages/viewer/src/components/viewer-pin-tool/readme.md
Adding more usage docs for pins.
https://vertexvis.atlassian.net/browse/PLAT-1981
> [PLAT-1981] More usage docs for pins

- packages/viewer/src/components/scene-tree/lib/controller.ts
Resolves the issue that the closed subscription stream was not present on the state in the case of a reconnect.
> [PLAT-2258] Setting the correct stream state

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.spec.tsx
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- yarn.lock
Passes a selection value according to the updated protobufs. See https://github.com/Vertexvis/vertex-public-protobufs/pull/175.
https://vertexvis.atlassian.net/browse/PLAT-2596
> [PLAT-2596] Selection operation values

- packages/viewer/src/lib/transforms/transformation-delta.ts
Updates the documentation & variable names, based on the feedback here: https://github.com/Vertexvis/vertex-web-sdk/pull/494#pullrequestreview-1419385005
> [PLAT-2808] Update variables/documentation for the orthogonal candidate

- examples/align-two-surfaces/index.html
- examples/align-two-surfaces/main.js
- examples/camera-manipulations/index.html
- examples/camera-manipulations/main.js
- examples/helpers.js
- examples/loading-models/index.html
- examples/loading-models/main.js
- examples/metadata-operations/index.html
- examples/metadata-operations/main.js
- examples/metadata-operations/styles.css
- examples/phantom-parts/index.html
- examples/phantom-parts/main.js
- examples/picking/index.html
- examples/picking/main.js
- examples/work-instructions/instructions.js
- examples/work-instructions/steps.js
Includes example of how to perform alterations on items matching metadata.
https://vertexvis.atlassian.net/browse/PLAT-3069
> [PLAT-3069] Add example for altering items by metadata

- examples/end-items/index.html
- examples/end-items/main.js
- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/operations.spec.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/operations.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
This PR adds support for end item operations, such that parts can be set as end item. An example demonstrating how the feature can be used is also included.
Verify that parts can be set as end item.
None
Part operations
None
> [PLAT-3103] Support end item operations

- examples/end-items/index.html
- examples/end-items/main.js
This PR updates the example for end items.
Verify that the end item example works as expected.
None
Examples
None
> [PLAT-3103] Update end items example

- README.md
- examples/align-two-surfaces/index.html
- examples/camera-manipulations/index.html
- examples/custom-interactions/index.html
- examples/custom-interactions/main.js
- examples/end-items/index.html
- examples/end-items/main.js
- examples/loading-models/index.html
- examples/loading-models/main.js
- examples/metadata-operations/index.html
- examples/phantom-parts/index.html
- examples/picking/index.html
- examples/picking/main.js
- examples/picking/styles.css
- examples/work-instructions/index.html
- examples/work-instructions/instructions.js
- examples/work-instructions/main.js
- examples/work-instructions/steps.js
This PR updates all our SDK examples to use the latest version of the SDK.  Further, this updates the 'picking' example to use selection alterations.
Verify all the examples work as expected.
None
Examples
None
> [PLAT-3291] Update examples

- package.json
- packages/viewer/package.json
- packages/viewer/stencil.config.ts
Enables the custom distribution to be tree-shakable again. The bundle size was getting rather large, and the entire SDK was getting added as an entire chunk.
> [PLAT-2503] Tree Shakable custom-elements

- examples/walk-mode/index.html
- examples/walk-mode/main.js
Adds a `walk-mode` example to the examples directory to demonstrate work introduced in #534.
- Load the example and verify the instructions work as expected
N/A
N/A
N/A
> [PLAT-2432] Add walk mode example

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/__tests__/operations.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/operations.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
Adds alteration operation to change renditions.
https://vertexvis.atlassian.net/browse/PLAT-3263
> [PLAT-3263] Add operations to change renditions

- lerna.json
- packages/viewer-react/package.json
- packages/viewer-vue/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Changes Include:
- A viewer property to enable/disable temporal refinement
- A new event on the box query tool to emit an event when the controller changes.
Bug Fixes Include:
- An export of the `model` type for volume selection
- Zoom & Twist Touch Interactions 
- React Dev Dependencies
> Release v0.20.1

- packages/viewer/index.html
- packages/viewer/src/components/scene-tree/readme.md
- packages/viewer/src/components/viewer-hit-result-indicator/readme.md
> [PLAT-4007] Updating Demo Stream Key

- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
Fixes a function context issue after some cleanup changes in #583.
- Verify the `EXPERIMENTAL_undoKeybindings` properly performs an undo
N/A
N/A
N/A
> [PLAT-3970] Fix undo function context

- examples/end-items/index.html
- examples/helpers.js
- examples/picking/index.html
- examples/transform-widget/index.html
- packages/viewer/src/components/viewer-transform-widget/readme.md
> Updated Demo Stream Key

- packages/viewer/src/components/viewer-annotation-callout/readme.md
- packages/viewer/src/components/viewer-annotation-callout/viewer-annotation-callout.css
- packages/viewer/src/components/viewer-annotation-callout/viewer-annotation-callout.spec.tsx
- packages/viewer/src/components/viewer-annotation-callout/viewer-annotation-callout.tsx
- packages/viewer/src/lib/annotations/annotation.ts
- packages/viewer/src/lib/mappers/__tests__/annotation.spec.ts
- packages/viewer/src/lib/mappers/annotation.ts
- packages/viewer/src/testing/annotations.ts
- yarn.lock
This uses the new protos which include messages for the different types of annotations.
https://vertexvis.atlassian.net/browse/PLAT-4273
> [PLAT-4273] Update parsing of annotations to use new protos

- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.tsx
These changes enable right clicking on the pin label element to allow for right click / delete.
Verify a right click propagates up the dom from a text label
> [PLAT-4416] Text Label Right Click fix

- examples/align-two-surfaces/index.html
- examples/align-two-surfaces/main.js
- examples/camera-manipulations/index.html
- examples/camera-manipulations/main.js
- examples/custom-interactions/index.html
- examples/end-items/index.html
- examples/loading-models/index.html
- examples/loading-models/main.js
- examples/metadata-operations/index.html
- examples/metadata-operations/main.js
- examples/phantom-parts/index.html
- examples/picking/index.html
- examples/transform-widget/index.html
- examples/walk-mode/index.html
- examples/work-instructions/index.html
- examples/work-instructions/instructions.js
Updates the examples to user the latest released version of the package.
> [PLAT-4505] Update examples to use the latest released version

- packages/viewer/package.json
- packages/viewer/src/lib/model-views/mapper.ts
- packages/viewer/src/testing/modelViews.ts
- yarn.lock
Adds a mapping for the `camera` field on a `ModelView`.
- Verify that the `camera` property comes back on a list of model views
N/A
Listing model views
N/A
> [PLAT-4666] Include Model View camera

- packages/viewer/src/lib/model-views/types.ts
Updates the exported `ModelView` type to include the `camera` field.
N/A
N/A
N/A
N/A
> [PLAT-4666] Include camera in exported type

- packages/viewer/src/lib/model-views/controller.ts
- yarn.lock
Adds option to filter item model views with annotations.
https://vertexvis.atlassian.net/browse/PLAT-4800
> [PLAT-4800] Item model views with annotations filter

- packages/utils/src/mapper.ts
Updates the mapper util to support 10 arguments.
- Verify stream attributes can be mapped as expected
N/A
N/A
N/A
> Update typing for ten arguments

- examples/align-two-surfaces/main.js
- examples/end-items/main.js
- examples/metadata-operations/main.js
- examples/phantom-parts/main.js
- examples/picking/main.js
- examples/transform-widget/main.js
- examples/work-instructions/instructions.js
- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/components/scene-tree/lib/viewer-ops.ts
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.spec.tsx
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.tsx
- packages/viewer/src/components/viewer-transform-widget/readme.md
- packages/viewer/src/index.ts
- packages/viewer/src/lib/model-views/controller.ts
- packages/viewer/src/lib/pmi/controller.ts
- packages/viewer/src/lib/scenes/__tests__/operations.spec.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/index.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/operations.ts
- packages/viewer/src/lib/scenes/queries.ts
- packages/viewer/src/lib/scenes/raycaster.ts
- packages/viewer/src/lib/scenes/scene.ts
- packages/viewer/src/lib/volume-intersection/__tests__/controller.spec.ts
- packages/viewer/src/lib/volume-intersection/controller.ts
- yarn.lock
This PR includes support for the new scene alteration payload and a new scene.elements() method.
Verify scene item interactions continue to work as expected
- Includes support for the new scene alteration payload
- Includes new scene.elements() method
Interacting with scene items
None
> [PLAT-5090] Use new scene alteration payload

- examples/align-two-surfaces/index.html
- examples/align-two-surfaces/main.js
- examples/camera-manipulations/index.html
- examples/camera-manipulations/main.js
- examples/custom-interactions/index.html
- examples/end-items/index.html
- examples/loading-models/index.html
- examples/loading-models/main.js
- examples/metadata-operations/index.html
- examples/metadata-operations/main.js
- examples/phantom-parts/index.html
- examples/picking/index.html
- examples/transform-widget/index.html
- examples/walk-mode/index.html
- examples/work-instructions/index.html
- examples/work-instructions/instructions.js
Updates the version requested by our examples to v0.23.x after #645 released v0.23.0. 
- Verify examples continue to work as expected
N/A
N/A
N/A
> [PLAT-5570] Update examples to 0.23.x

- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.spec.tsx
- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.tsx
- packages/viewer/src/lib/measurement/interactions.ts
- packages/viewer/src/lib/types/entities.ts
This PR includes improvements to measurement in order to ensure consistent results.
Verify precise and point-to-point measurement works as expected.
None
Measurement
None
> [PLAT-5767] Measurement improvements

- examples/scene-tree-columns/index.html
Using latest code to show the partial filter results banner.
> [PLAT-6168] Using latest canary for the example for columns

- packages/viewer/src/components/scene-tree-notification-banner/scene-tree-notification-banner.css
Slightly reducing the padding of the left notification icon.
Before:
After:
> [PLAT-6168] Reducing padding on the left icon

- packages/viewer/src/components/scene-tree/scene-tree.tsx
Text change for the partial results banner
> [PLAT-6168] Changing text for the partial results banner

- packages/viewer/src/index.ts
- packages/viewer/src/lib/scene-items/index.ts
- packages/viewer/src/lib/transforms/index.ts
- packages/viewer/src/lib/transforms/transformation-delta.ts
- packages/viewer/src/lib/transforms/util.ts
This PR exports the SceneViewItem type as well as several helpers around transforms.
Verify the items can be imported into consuming applications
None
None
None
> [PLAT-5789] Export transform helpers and SceneViewItem
