Vertexvis/vertex-web-sdk

- packages/graphics3d/yarn.lock
- packages/network/yarn.lock
- packages/utils/yarn.lock
- packages/vertex-api/yarn.lock
Updates yarn.lock files to point to the correct registry for our publicly available build tooling.
This was done manually, rather than entirely regenerating the lockfiles.
- Running `yarn install` followed by `yarn bootstrap` should successfully pull all build tooling
> [SDK-637] Point to correct registry

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/scenes/index.ts
- packages/viewer/src/scenes/scene.ts
Adds a `Scene` class that will be used in future PRs to modify a loaded scene. Example:
```ts
const scene = await viewer.scene();
// Perform a camera operation
scene.camera().position(1, 2, 3);
// Perform a hit operation
scene.raycaster().hit({x: 1, y: 2});
```
https://jira.vertexvis.net/browse/SDK-737
Unit tests
N/A
N/A
N/A
> [SDK-737] Add Scene class that will be used to modify a loaded scene

- .github/workflows/ci.yml
- packages/stream-api/src/streamApi.ts
- packages/viewer/package.json
- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/interactions/__tests__/interactionApi.spec.ts
- packages/viewer/src/interactions/interactionApi.ts
- packages/viewer/src/scenes/__tests__/camera.spec.ts
- packages/viewer/src/scenes/__tests__/scene.spec.ts
- packages/viewer/src/scenes/camera.ts
- packages/viewer/src/scenes/index.ts
- packages/viewer/src/scenes/scene.ts
- packages/viewer/src/types/__fixtures__/index.ts
- packages/viewer/src/types/frame.ts
- packages/viewer/src/types/frameCamera.ts
- packages/viewer/src/types/index.ts
- packages/viewer/yarn.lock
This adds operations to the scene to modify its camera. Example usage:
```ts
const scene = await viewer.scene();
// update the position
let camera = scene.camera().update({ position: Vector3.forward() });
// rotate around an axis
camera = camera.rotateAroundAxis(Math.PI / 2, Vector3.up());
// fit to a bounding box
camera = camera.fitToBoundingBox(BoundingBox.create(...));
// finally queue a frame to render
camera.render()
```
https://jira.vertexvis.net/browse/SDK-738
Unit tests
N/A
N/A
N/A
> [SDK-738] Add operations to modify the scene camera

- packages/stream-api/src/__tests__/streamApi.spec.ts
- packages/stream-api/src/streamApi.ts
e0e65d93315efe4f4863c496010c63c18be26987 did not include the `websocket.send` in the `sendWithRequestId` method so the hit items does not submit the request and return data
https://jira.vertexvis.net/browse/SDK-735
see https://github.com/Vertexvis/vertex-web-sdk/pull/14
n/a
n/a
n/a
> restore websocket.send to sendRequestWithId

- packages/stream-api/src/__tests__/streamApi.spec.ts
- packages/stream-api/src/streamApi.ts
- packages/stream-api/src/types.ts
- packages/utils/src/mappedTypes.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/scenes/__tests__/raycaster.spec.ts
- packages/viewer/src/scenes/raycaster.ts
- stream-api should be able to tag a request as a fire-and-forget type of requests. In this scenario, a returned promise should resolve immediately without a response.
- stream-api should be able to tag a request as a request-response. In this scenario, a returned promise should resolve with the response it receives from FSS, or with an error.
- stream-api should expose typings of request bodies with optional fields marked as nullable, and required fields marked as non-null.
https://jira.vertexvis.net/browse/SDK-740
TBD
TBD
TBD
n/a
> [SDK-740] stream api improvements

- lerna.json
- scripts/detect_publish.sh
- scripts/release.sh
- scripts/utils.sh
Making a couple changes with our release script with the new Lerna process:
* `lerna version` will only run from within a `release-temp/*` branch
* Remove the git commit message. Prior script would include the changed version of each package. Since we're using fixed versioning, all packages should have the same version.
* You can only initiate a release now from the `master` branch.
* Pushed branch has the format: `release/v[major].[minor].[patch]`
1. Merge
2. Run `yarn release`
N/A
N/A
N/A
> [SDK-797] Release script changes

- scripts/release.sh
Fixes a bug with checking that the release script is being run on a master branch.
N/A
N/A
N/A
N/A
> [SDK-797] Fix release script check to verify master branch

- .github/workflows/master.yml
- package.json
- scripts/release.sh
Should fix an issue where packages aren't published on merge, because GH lacks permissions to publish. Also fixes an issue where the versions in READMEs were not being updated to new versions.
1. Create a release
2. Merge
3. Should be published to NPM
N/A
N/A
N/A
> [SDK-797] Fix NPM token

- lerna.json
- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/viewer/package.json
- packages/viewer/readme.md
Release v0.5.0 which includes breaking changes to support stream keys.
https://vertexvis.atlassian.net/browse/SDK-824
> Release v0.5.0

- packages/viewer/src/components/viewer/viewer.tsx
If a stream disposable is present, and the client has loaded another stream key, we should dispose of the prior stream connection.
https://vertexvis.atlassian.net/browse/SDK-841
Switching models via the `.load()` should not switch back to the old model 
N/A
N/a
N/A
> [SDK-841] dispose of stream when loading a new stream key

- packages/viewer/src/components/viewer/viewer.spec.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/config/config.ts
- packages/viewer/src/config/environment.ts
Expose production environment for vertex web sdk and use it as the default. 
To leverage the viewer and use a development environment, you will have to pass the env to the viewer. 
```
const viewer = document.querySelector('#viewer');
viewer.configEnv = 'platdev';
```
Ensure rendering works for platprod and platdev
N/A
N/A
N/A
> [SDK-850] Default to prod environment for websdk

- packages/viewer/src/interactions/interactionApi.ts
- packages/viewer/src/scenes/__tests__/camera.spec.ts
- packages/viewer/src/scenes/camera.ts
Add option to omit responses for camera updates. This will disable a server acknowledgement and is helpful to reduce network congestion for performance sensitive situations, such as interactions.
By default, responses will be omitted for camera interactions.
https://vertexvis.atlassian.net/browse/SDK-885
> [SDK-885] Omit responses for interaction camera requests

- packages/stream-api/package.json
- packages/stream-api/src/streamApi.ts
- packages/stream-api/yarn.lock
- packages/viewer/package.json
- packages/viewer/src/commands/__tests__/streamCommands.spec.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/testing/frameStreamingClient.ts
- packages/viewer/src/types/frame.ts
- packages/viewer/yarn.lock
Includes updates for breaking protobuf changes that were introduced as part of https://github.com/Vertexvis/frame-streaming-protos/pull/34. 
https://vertexvis.atlassian.net/browse/SDK-896
Verify that models are rendered in the viewer.
N/A
N/A
N/A
> [SDK-896] Update the viewer to use new message for drawing frames

- packages/stream-api/jest.config.js
- packages/stream-api/package.json
- packages/stream-api/src/__tests__/streamApi.spec.ts
- packages/stream-api/src/connection.ts
- packages/stream-api/src/index.ts
- packages/stream-api/src/streamApi.ts
- packages/stream-api/src/types.ts
- packages/stream-api/src/url.ts
- packages/stream-api/src/webSocketClient.ts
- packages/stream-api/yarn.lock
- packages/utils/src/mappedTypes.ts
- packages/viewer/package.json
- packages/viewer/src/__mocks__/@vertexvis/stream-api.ts
- packages/viewer/src/commands/__tests__/streamCommands.spec.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/components/viewer/__mocks__/utils.ts
- packages/viewer/src/components/viewer/utils.ts
- packages/viewer/src/components/viewer/viewer.css
- packages/viewer/src/components/viewer/viewer.spec.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/yarn.lock
Generates JPEG frames using the background color of the viewer. The viewer background color can be set using the `--viewer-background` CSS variable:
```css
.viewer {
--viewer-background: red;
}
```
https://vertexvis.atlassian.net/browse/SDK-898
You shouldn't see a light gray background with rendered frames.
N/A
N/A
https://github.com/Vertexvis/frame-streaming-service/pull/83
> [SDK-898] Generate frames using the background color of the viewer

- packages/viewer/src/commands/__tests__/streamCommands.spec.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/index.html
- packages/viewer/src/scenes/__tests__/scene.spec.ts
- packages/viewer/src/scenes/queries.ts
- packages/viewer/src/scenes/scene.ts
You should be able to do multiple operations in one transactional request to the server. IE, if you want to do a show only on an item, today you would have to do two separate executions:
```
await scene.items().where(q => q.all()).hide().execute();
await scene.items().where(q => q.withItemId(ITEM_ID)).show().execute();
```
This PR includes changes to allow you to pass multiple operations inside one execution context. This will break syntax of existing consumers, but will break type checking if you happen to be using typescript. 
Introducing the new syntax for item operations:
```
scene
.items(
op => [
op.where(q => q.all()).hide(),
op.where(q => q.withItemId(itemId).or().withSuppliedId(suppliedId)).show(),
op.where(q => q.all()).materialOverride(ColorMaterial.fromHex("#ff1122"))
]) …
```
> [SDK-796] Support for Transactional Queries

- packages/utils/src/__tests__/async.test.ts
- packages/viewer/src/index.html
- packages/viewer/src/metrics/timing.ts
- packages/viewer/src/types/__tests__/typeGuards.spec.ts
- packages/viewer/src/types/index.ts
- packages/viewer/src/types/typeGuards.ts
Angular appears to use it's own version of a Promise, and our type check would fail. Adding a type guard to check if an object is promise like.
https://vertexvis.atlassian.net/browse/SDK-954
1. Use viewer in an Angular app.
2. Validate that the viewer loads a model and is interactable.
> [SDK-954] Fix check for promises used in Angular

- packages/viewer/src/components/viewer/viewer.spec.ts
- packages/viewer/src/components/viewer/viewer.tsx
Fixes a bug where a `StateError` is thrown when attempting to perform a scene operation immediately after loading a scene.
https://vertexvis.atlassian.net/browse/SDK-958
```js
await viewer.load('stream-key');
await viewer.scene();
```
> [SDK-958] Fix exception when executing scene op after load

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/rendering/__tests__/remote.spec.ts
- packages/viewer/src/rendering/canvas.ts
- packages/viewer/src/rendering/remote.ts
- packages/viewer/src/scenes/camera.ts
These changes are to include some better error handling, as well as not throwing console exceptions on the event that the client is dropping frames. After investigation into the issue noted in the ticket, I noticed that when this event was happening, it happened when the frames got backed up, and then the user switches scenes. This would then close the old WS, and open a new one. This led me to find that the issue was that somewhere the client was resolving the promises, even though none of the responses were coming from the server. The root issue, pertains to setting a timeout on the frames. I am proposing in these changes that we remove this timeout so that on the event of dropped frames these errors don't show up to the client.
If there is an argument for keeping the timeout in, …
> [SDK-962] Resolve Console Errors

- packages/stream-api/src/__tests__/paramsBuilder.spec.ts
- packages/stream-api/src/__tests__/settings.spec.ts
- packages/stream-api/src/index.ts
- packages/stream-api/src/paramsBuilder.ts
- packages/stream-api/src/settings.ts
- packages/stream-api/src/streamApi.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/components/viewer/viewer.spec.ts
- packages/viewer/src/config/config.ts
- packages/viewer/src/types/flags.ts
Exposes settings and flags to configure the delivery of frames.
https://vertexvis.atlassian.net/browse/SDK-997
```js
const viewer = document.querySelector('#viewer');
viewer.config = {
EXPERIMENTAL_frameDelivery: {
packetLossThreshold: 1,
},
};
```
This should pass a URL param on the websocket to configure the packet loss threshold.
> [SDK-997] Add flags and settings for configuring frame delivery

- packages/stream-api/src/index.ts
- packages/stream-api/src/settings.ts
- packages/viewer/src/commands/streamCommands.ts
- packages/viewer/src/config/config.ts
- packages/viewer/src/types/flags.ts
- packages/viewer/tsconfig.json
Adding options to configure adaptive rendering.
https://vertexvis.atlassian.net/browse/SDK-1015
Rendering without adaptive rendering should not be impacted.
> [SDK-1015] Add configuration options for adaptive rendering

- packages/geometry/package.json
- packages/stream-api/package.json
- packages/utils/package.json
Adding a peer dependency for `tslib` for the utils package. This should give a warning when trying to add `@vertexvis/utils` and the project doesn't have `tslib` as a dependency.
https://vertexvis.atlassian.net/browse/SDK-1037
> [SDK-1037] Add tslib as peer dependency to utils package

- packages/stream-api/package.json
- packages/stream-api/src/webSocketClient.ts
- packages/stream-api/yarn.lock
- packages/viewer/package.json
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/metrics/timing.ts
- packages/viewer/src/rendering/__tests__/canvas.spec.ts
- packages/viewer/src/rendering/canvas.ts
- packages/viewer/yarn.lock
Updates the protos so they include the correct type for item supplied ids in hit results. Also includes a fix for update dimensions causing warnings in FSS. This call was being made before the stream was started in FSS.
https://vertexvis.atlassian.net/browse/SDK-1064
```html
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
<meta charset="utf-8" />
<meta
name="viewport"
content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0"
/>
<title>Stencil Component Starter</title>
<script type="module" src="/build/viewer.esm.js"></script>
<script nomodule src="/build/viewer.js"></script>
<link rel="stylesheet" href="/build/viewer.css" />
<style>
html,
body {
width: 100%;
height: 100%;
padding: 0;
margin: 0;
}
#viewer {
width: 100%;
height: 100%;
}
</style>
<script …
```
> [SDK-1064] Update protos to include item supplied ids in hit results

- packages/viewer/src/types/flags.ts
Defaults the flags to on for adaptive rendering and rate limited frame delivery.
https://vertexvis.atlassian.net/browse/SDK-1089
> [SDK-1089] Enable flags for adaptive rendering and rate limited delivery

- packages/viewer/src/components/viewer/viewer.spec.ts
- packages/viewer/src/components/viewer/viewer.tsx
Fixes an issue with loading of a second scene in the viewer where the `streamId` was not cleared out and would cause a problem opening a second connection. With the `streamId` and `resource` defined, the WS connection would attempt to reconnect when closed, rather than start a stream, which introduced a problem when a `reconnect` happened before the `startStream`, and cause the second connection to fail.
https://vertexvis.atlassian.net/browse/SDK-1161
- Test loading the html in the above ticket with these changes
```
-  <link rel="stylesheet" href="https://unpkg.com/@vertexvis/viewer@latest/dist/viewer/viewer.css" />
-  <script type="module" src="https://unpkg.com/@vertexvis/viewer@latest/dist/viewer/viewer.esm.js"></script>
-  <script nomodule …
```
> [SDK-1161] Clear streamId on viewer.dispose()

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/config/config.ts
- packages/viewer/src/interactions/__tests__/tapInteractionHandler.spec.ts
- packages/viewer/src/interactions/interactionApi.ts
- packages/viewer/src/interactions/tapInteractionHandler.ts
- packages/viewer/src/interactions/touchInteractionHandler.ts
- packages/viewer/src/types/events.ts
- packages/viewer/src/types/index.ts
Adds support for a `doubletap` and `longpress` event. These both default to allowing a second tap to trigger a `doubletap` if it occurs within 500ms, and triggering a `longpress` if a mousedown/touchstart occur and 500ms pass before a mouseup/touchend are received. These durations are configurable through the `viewer.config` property by passing:
```javascript
viewer.config = {
events: {
longPressThreshold: {ms},
doubleTapThreshold: {ms}
}
}
```
Also made a small adjustment to the touch interaction handler for rotating the camera to allow for single pixel movements after you've initiated a rotation (by moving a distance >= 2 pixels). This allows for more fine-tuned movements of the camera during a touch-based camera interaction.
https://vertexvis.atlassian.net/browse/SDK-1147
- Test adding …
> [SDK-1147] Support for double tap and long press events

- packages/stream-api/package.json
- packages/stream-api/yarn.lock
- packages/viewer/package.json
- packages/viewer/yarn.lock
When a part revision is associated to a scene, you will now see the revision, part, and supplied revision Id on the hit result. 
https://vertexvis.atlassian.net/browse/SDK-1232
- on a hit response for a scene created with part revisions, do a console.log of the hit result. You should see the part id, part revision and supplied part revision if the data is present on the entity.
> [SDK-1232] Bumping version of protos to support returning part ids on a hit result

- packages/viewer/readme.md
- packages/viewer/src/index.html
In some browsers the custom elements are not yet defined. We will want to wait for those prior to trying to access any custom elements on our web component. 
https://vertexvis.atlassian.net/browse/SDK-1025
Ensure the regression steps on SDK-1025 do not happen any more with this change. Note, you'll need to update the html in the ticket with the code referenced in the example to get this to work. 
N/A
N/a
N/A
> [SDK-1025] Update reference to wait for custom element to be defined

- packages/utils/src/color.ts
The alpha component isn't used when converting color to a hex code. Omit it from the type.
https://vertexvis.atlassian.net/browse/SDK-1249
> [SDK-1249] Omit alpha from color in hex string converter

- packages/viewer/src/scenes/raycaster.ts
Return type was incorrect. Should be `IHitItemsResult | undefined`. If `void` is used, then you need to provide a type guard to see if a `IHitItemsResult` is returned.
https://vertexvis.atlassian.net/browse/SDK-1249
> Change return type of hit items to use undefined

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/rendering/__tests__/canvas.spec.ts
- packages/viewer/src/rendering/canvas.ts
- packages/viewer/src/types/flags.ts
Adds a flag to log the current and average (5s) frame rate to the console. Enable by:
```ts
viewer.config = {
flags: { logFrameRate: true }
}
```
https://vertexvis.atlassian.net/browse/SDK-1302
> [SDK-1302] Add logging for frame rate

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/interactions/__tests__/interactionApi.spec.ts
- packages/viewer/src/rendering/canvas.ts
- packages/viewer/src/scenes/__tests__/scene.spec.ts
- packages/viewer/src/scenes/scene.ts
There wasn't a way to get the loaded scene view id programmatically in the viewer. This adds that + some logging about connections.
https://vertexvis.atlassian.net/browse/SDK-1249
> [SDK-1249] Expose the scene view id from the viewer

- packages/stream-api/package.json
- packages/stream-api/yarn.lock
- packages/viewer/package.json
- packages/viewer/src/commands/streamCommandsMapper.ts
- packages/viewer/src/scenes/operations.ts
- packages/viewer/src/scenes/scene.ts
- packages/viewer/yarn.lock
Adds support for selection operations.
```
const scene = await viewer.scene();
scene.items(op => 
op.where(q => q.withItemId('id').select('#ff0000'))
);
scene.items(op => 
op.where(q => q.withItemId('id').deselect())
);
```
https://vertexvis.atlassian.net/browse/SDK-1311
- Test applying selection through the SDK
- Test deselecting the same item
N/A
N/A
N/A
> [SDK-1311] Support selection operations

- packages/stream-api/package.json
- packages/stream-api/src/streamApi.ts
- packages/stream-api/yarn.lock
- packages/viewer/package.json
- packages/viewer/src/commands/streamCommandsMapper.ts
- packages/viewer/src/rendering/__tests__/remote.spec.ts
- packages/viewer/src/rendering/remote.ts
- packages/viewer/src/scenes/__tests__/camera.spec.ts
- packages/viewer/src/scenes/camera.ts
- packages/viewer/src/types/animation.ts
- packages/viewer/src/types/flyToOptions.ts
- packages/viewer/src/types/index.ts
- packages/viewer/yarn.lock
Changes to support animations on render.
https://vertexvis.atlassian.net/browse/SDK-1335
https://vertexvis.atlassian.net/browse/SDK-1052
See test plan on FSS pr for comprehensive test plan:
https://github.com/Vertexvis/frame-streaming-service/pull/143
Can be tested in the viewer by adding a duration in ms in the camera render func:
```
await scene.camera().update(updateCamera).render({
animation: {
milliseconds: 500
}
});
```
I also added the support for the fly to operation that supports either a bounding box, item id, suppliedId or camera.
```
camera
.flyTo(q => q.withSuppliedId('suppliedId'))
.render({
animation: {
milliseconds: 500,
},
});
```
https://github.com/Vertexvis/frame-streaming-service/pull/143
> [SDK-1335][SDK-1052][SDK-1355] Animations on Camera Render, and support for fly to

- packages/stream-api/package.json
- packages/stream-api/yarn.lock
- packages/viewer/package.json
- packages/viewer/src/scenes/__tests__/camera.spec.ts
- packages/viewer/src/scenes/camera.ts
- packages/viewer/src/scenes/scene.ts
- packages/viewer/src/types/__fixtures__/index.ts
- packages/viewer/src/types/frame.ts
- packages/viewer/yarn.lock
These changes introduce adding the visible bounding box as present on the scene attributes on the frame. The ticket called for `.viewAll` to be a promise with an executable, and I'm proposing a slightly different direction here to allow for consistent behavior with automations as well as having one executable. 
Pivoting back to have `viewAll` be an executable would not be a big change if we choose to go that route. I thought this approach was a little cleaner and more consistent with the patterns in our SDK.
A developer would perform a `viewAll` operation by doing the following:
```
await scene.camera().viewAll().render()
```
Alternatively, you can animate to the view all position by doing the following:
```
await scene.camera().viewAll().render({ animation: { milliseconds: 1500 }})
``` …
> [SDK-1300] Support View All visible parts

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/types/__tests__/loadableResource.spec.ts
- packages/viewer/src/types/loadableResource.ts
Adds support for starting a stream using a scene view state. This is provided using a query param on the `src` urn:
```
urn:vertexvis:stream-key:<key>?scene-view-state=<state-id>
```
https://vertexvis.atlassian.net/browse/SDK-1321
- Test starting a stream with a scene view state id provided
Loading of stream keys
N/A
https://github.com/Vertexvis/frame-streaming-service/pull/153
> [SDK-1321] Support starting from scene view state

- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/interactions/__tests__/flyToPartKeyInteraction.spec.ts
- packages/viewer/src/interactions/flyToPartKeyInteraction.ts
- packages/viewer/src/scenes/__tests__/camera.spec.ts
- packages/viewer/src/scenes/camera.ts
Making some small tweaks to our fly-to operation:
* Use Alt+Click to fly to part. This is inline with the keyboard shortcut in connect and should reduce key conflicts in Mac OS.
* Add a simpler object params to specify fly to part arguments.
https://vertexvis.atlassian.net/browse/SDK-1388
> [SDK-1388] Fly to tweaks

- .github/workflows/master.yml
- scripts/publish_release.sh
I'm seeing a couple errors when trying to publish a release. I think there's some concurrency issue between the canary and latest release scripts. This publishing the latest and canary versions into a single job.
* https://github.com/Vertexvis/vertex-web-sdk/runs/1914816212?check_suite_focus=true
* https://github.com/Vertexvis/vertex-web-sdk/runs/1914664953?check_suite_focus=true
https://vertexvis.atlassian.net/browse/SDK-1388
> [SDK-1388] Fix concurrent error with dist tags and publishing releases

- scripts/detect_release.sh
Saw a bug in our detect release script that was using tags to detect if a release needed to be performed. This instead checks if there's a published version in NPM.
https://vertexvis.atlassian.net/browse/SDK-1391
> [SDK-1391] Check NPM if we need to run a release

- .github/workflows/master.yml
This sequences the publishing of release versions to NPM after canary deploys are run.
https://vertexvis.atlassian.net/browse/SDK-1391
> [SDK-1391] Run publish-release after publish-canary is run

- packages/viewer/stencil.config.ts
Adds `extras` corresponding to necessary polyfills for Edge <= 18 to allow for usage in the Xamarin SDK.
https://vertexvis.atlassian.net/browse/SDK-1429
- Test on Windows with EdgeHTML <= 18 replacing the `DOMContentLoaded` listener with the following
```typescript
import { applyPolyfills } from '/dist/esm/polyfills/index.js';
import { defineCustomElements } from '/dist/esm/loader.js';
window.addEventListener('DOMContentLoaded', () => {
applyPolyfills().then(() => defineCustomElements(window).then(() => main()))
});
```
N/A
N/A
N/A
> [SDK-1429] Stencil 2.0 support for Edge <= 18

- packages/viewer/src/interactions/baseInteractionHandler.ts
Prevent default on wheel events and fix scrolling for firefox.
https://vertexvis.atlassian.net/browse/SDK-963
https://vertexvis.atlassian.net/browse/SDK-1517
- Test scrolling in the viewer with a page that's larger than the browser window
- Page should not scroll, and model should zoom
- Test scrolling on Firefox
N/A
N/A
N/A
> [SDK-1517] [SDK-963] Prevent window scroll when zooming and fix zoom on firefox

- packages/viewer/src/interactions/__tests__/mouseInteractionHandler.spec.ts
- packages/viewer/src/interactions/baseInteractionHandler.ts
- packages/viewer/src/interactions/tapInteractionHandler.ts
Corrects a couple behaviors from the SDK that were resulting in seemingly lost `tap` events:
- Performs a drag immediately after beginning an interaction since we will have moved the threshold amount
- Emits a tap when a longpress occurred, and adds both a `longPress` and `doubleTap` property to the tap event info to indicate whether it was part of either interaction
https://vertexvis.atlassian.net/browse/SDK-1513
- Test tap events (longpress, doubletap, tap)
- Test interactions, there should no longer be a "dead zone" where a tap is not emitted and an interaction doesn't begin visually
Tap events, interactions
N/A
N/A
> [SDK-1513] Perform drag when beginning interaction

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/interactions/__tests__/mouseInteractionHandler.spec.ts
- packages/viewer/src/interactions/__tests__/tapInteractionHandler.spec.ts
- packages/viewer/src/interactions/__tests__/twistInteractionHandler.spec.ts
- packages/viewer/src/interactions/baseInteractionHandler.ts
- packages/viewer/src/interactions/mouseInteractionHandler.ts
- packages/viewer/src/interactions/pointerInteractionHandler.ts
- packages/viewer/src/interactions/tapInteractionHandler.ts
- packages/viewer/src/types/interactions.ts
Introduces a delay before we register a pointer interaction as a camera manipulation (default to 150ms). Within this delay, a pointerdown + pointerup will be considered a tap regardless of the amount of movement, and an interaction will not occur. 
In the case of that the timer elapses and an interaction begins, we will transform the camera to reflect the amount of movement so far to make things feel more responsive.
Here are a couple videos to demonstrate the change:
Before:
https://user-images.githubusercontent.com/5252480/112912600-7faa0680-90bd-11eb-9b3e-f0d6392e65de.mov
After:
https://user-images.githubusercontent.com/5252480/112912605-833d8d80-90bd-11eb-82eb-7630ad060285.mov
https://vertexvis.atlassian.net/browse/SDK-1512
- Test tap behavior (tap, doubletap, longpress)
- Test …
> [SDK-1512] Support quick tap events

- packages/viewer/package.json
- packages/viewer/src/commands/streamCommandsMapper.ts
- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree/lib/__tests__/controller.spec.ts
- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/scene-tree/lib/viewer-ops.ts
- packages/viewer/src/components/scene-tree/readme.md
- packages/viewer/src/components/scene-tree/scene-tree.css
- packages/viewer/src/components/scene-tree/scene-tree.spec.ts
- packages/viewer/src/components/scene-tree/scene-tree.tsx
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/scenes/__tests__/operations.spec.ts
- packages/viewer/src/scenes/__tests__/scene.spec.ts
- packages/viewer/src/scenes/colorMaterial.ts
- packages/viewer/src/scenes/operations.ts
- packages/viewer/src/scenes/queries.ts
- packages/viewer/src/scenes/scene.ts
- packages/viewer/stencil.config.ts
- yarn.lock
Adds support for selection in the scene tree. By default, selecting a row in the tree will select the item that it's mapped to. Developers can disable this behavior by doing `<vertex-scene-tree selection-disabled />`. If disabled, you can programmatically perform selection with the following APIs:
* `SceneTree.selectItem(row, { append, color })`
* `SceneTree.deselectItem(row)`
https://vertexvis.atlassian.net/browse/SDK-1574
> [SDK-1574] Scene tree selection

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree/lib/__tests__/controller.spec.ts
- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/scene-tree/lib/dom.ts
- packages/viewer/src/components/scene-tree/lib/errors.ts
- packages/viewer/src/components/scene-tree/lib/grpc.ts
- packages/viewer/src/components/scene-tree/lib/testing.ts
- packages/viewer/src/components/scene-tree/readme.md
- packages/viewer/src/components/scene-tree/scene-tree.css
- packages/viewer/src/components/scene-tree/scene-tree.spec.ts
- packages/viewer/src/components/scene-tree/scene-tree.tsx
If the scene tree fails to load, we'll display an error message in the UI. Currently displays a custom message if the the scene tree has not been enabled for a scene. Will also emit on `error` event with details of why the tree did not load.
https://vertexvis.atlassian.net/browse/API-1771
> [API-1771] Display error message if scene tree not enabled

- packages/viewer/src/interactions/interactionApi.ts
Adjusts spin-center behavior when a mouse down occurs in whitespace.
This changes the previous default of rotating about the lookAt, which could be in an unexpected location after performing a number of spin-center rotations, to rotate about a point halfway between the near/far plane.
https://vertexvis.atlassian.net/browse/APP-2368
- Test spin-center when mouse down occurs in whitespace
- Test spin-center when mouse down occurs on the model
Spin center when mouse down occurs on the model
N/A
N/A
> [APP-2368] Adjust spin center whitespace behavior

- packages/viewer/src/components/scene-tree-row/readme.md
- packages/viewer/src/components/scene-tree-row/scene-tree-row.css
- packages/viewer/src/components/scene-tree-row/scene-tree-row.tsx
Fixes an issue where rows are being hidden if a node is marked is hidden in the scene tree and the application is using Tailwind. This happens because the row was setting a `hidden` css selector which is used in Tailwind. I've updated the implementation to use DOM attributes which can still be used to customize row styling using CSS attribute selectors.
https://vertexvis.atlassian.net/browse/API-1851
> [API-1851] Use attributes instead of selectors for row state

- packages/viewer/stencil.config.ts
Removes the React bindings for `vertex-scene-tree-row`. This component doesn't work as a React element when passed as a child to the scene tree, and is causing some confusion.
https://vertexvis.atlassian.net/browse/API-1853
> [API-1853] Omit React bindings for vertex-scene-tree-row

- packages/viewer/src/interactions/baseInteractionHandler.ts
- packages/viewer/src/interactions/interactionApi.ts
- packages/viewer/src/rendering/__tests__/coordinates.spec.ts
- packages/viewer/src/rendering/coordinates.ts
Adjusts the calculation of the world position when using spin-center. This approach uses similar logic to compute a ray to our rendering pipeline, and uses that in combination with the depth buffer value to determine a world position instead of using the camera matrices.
This resolves a couple issues related to camera zoom levels and click position.
https://vertexvis.atlassian.net/browse/APP-2376
- Test spin-center behavior
- Test at different zoom levels, and picking parts at the edge/corner of the screen
- Test when clicking in whitespace
N/A
N/A
N/A
> [APP-2376] Spin-center math adjustment

- packages/viewer/package.json
- packages/viewer/src/components/scene-tree-row/readme.md
- packages/viewer/src/components/scene-tree/lib/__tests__/binding.spec.ts
- packages/viewer/src/components/scene-tree/lib/binding.ts
- packages/viewer/src/components/scene-tree/readme.md
- yarn.lock
Fixes a bug where binding to a rows `selectionToggled` event wasn't working. This is because the browser treats HTML as case insensitive and will lowercase any attributes you set. To address this, properties and events can use dash case and it'll automatically be converted to camel case.
```html
<vertex-scene-tree class="tree">
<template>
<vertex-scene-tree-row prop:node={{row.node}} event:selection-toggled={{row.data.myHandler}}>
</vertex-scene-tree-row>
</template>
</vertex-scene-tree>
```
https://vertexvis.atlassian.net/browse/API-1852
> [API-1852] Fix bug with binding to camel cased events and props

- packages/viewer/src/interactions/__tests__/interactionApi.spec.ts
- packages/viewer/src/interactions/__tests__/tapInteractionHandler.spec.ts
- packages/viewer/src/interactions/interactionApi.ts
- packages/viewer/src/interactions/tapEventDetails.ts
- packages/viewer/src/interactions/tapInteractionHandler.ts
Adds a `buttons` property to `tap` events to allow for determining whether a `tap` is associated with a left-click or right-click. 
https://vertexvis.atlassian.net/browse/APP-2388
- Test that the `buttons` property appears on tap events as `1` for left-clicks and `2` for right-clicks
N/A
N/A
N/A
> [APP-2388] Provide buttons on tap events

- packages/stream-api/src/__tests__/time.spec.ts
- packages/stream-api/src/time.ts
- packages/viewer/src/rendering/timing.ts
Should help with reducing the number of logs for `"Possible erroneous send to receive timing"`. We were not adjusting the time offsets with the server. Note, this fix may still produce these logs but should hopefully be reported less.
https://vertexvis.atlassian.net/browse/API-1847
> [API-1847] Fix incorrect conversion of send to receive duration

- packages/viewer/src/interactions/__tests__/mouseInteractionHandler.spec.ts
- packages/viewer/src/interactions/baseInteractionHandler.ts
- packages/viewer/src/interactions/mouseInteractions.ts
Small fix to address an issue where scrolling to zoom would interrupt any following interaction that began before a final frame was received. 
Opted to go this route since it wound up being a fairly small/straightforward fix with our existing interactions rather than any refactoring, but open to thoughts on whether we should take some time to refactor this now.
https://vertexvis.atlassian.net/browse/APP-2183
- Test scroll to zoom
- Test drag-based zoom
- Test interactions after scrolling to zoom
- With this version, the interaction should no longer "freeze" after a couple seconds 
Zoom (drag/scroll)
N/A
N/A
> [APP-2183] Fix zoom interaction interrupting following interactions

- README.md
- packages/viewer/src/components/viewer/viewer.tsx
This is a potential fix for https://vertexvis.atlassian.net/browse/API-1878, which may be caused when quickly assigning stream attributes and changing the src of the stream, as might happen in React applications. This will eagerly disable the connection flag when `unload` is called which should prevent sending a message over a disconnecting websocket when `streamAttributes` is assigned.
https://vertexvis.atlassian.net/browse/API-1878
> [API-1978] Fix RTE when setting stream attributes and changing scene

- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement-components.tsx
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.css
- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.spec.tsx
This change makes it so the distance anchor labels are not included by default. This is to decouple the SDK styling from what is used in Connect. To include distance labels, create a template like so:
```html
<html>
<body>
<div>
<template id="distance-measurement">
<vertex-viewer-distance-measurement class="measurement">
<div slot="start-label" class="anchor-label">A</div>
<div slot="end-label" class="anchor-label">B</div>
</vertex-viewer-distance-measurement>
</template>
<vertex-viewer id="viewer" depth-buffers="all">
<vertex-viewer-measurements
distance-template-id="distance-measurement"
>
<vertex-viewer-measurement-tool></vertex-viewer-measurement-tool>
</vertex-viewer-measurements>
</vertex-viewer>
</div>
</body>
</html>
```
https://vertexvis.atlassian.net/browse/API-2009
> [API-2009] Don't show distance anchor labels by default

- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.tsx
Fixes a bug where measurements would show as invalid when rotating the model. This happened because we were checking validity on every prop change. We now only update validity when moving an anchor through user interaction.
https://vertexvis.atlassian.net/browse/API-2011
> [API-2011] Only update measurement validty on user interaction

- packages/viewer/src/components/viewer-measurements/viewer-measurements.spec.tsx
- packages/viewer/src/components/viewer-measurements/viewer-measurements.tsx
Fixes issue where a measurement will appear "valid" when adding a measurement where an anchor is off the model.
https://vertexvis.atlassian.net/browse/API-2016
> [API-2016] Fix bug with incorrect measurement validity

- packages/stream-api/src/encoder.ts
- packages/viewer/src/lib/mappers.ts
pbjs doesn't default scalar values during decoding, which was causing our mapper to throw an RTE. calling `toObject` will apply defaults to scalars.
https://vertexvis.atlassian.net/browse/API-2019
> [API-2019] Fix parsing of cross section

- packages/viewer/src/components/viewer/viewer.tsx
Fixes a bug when removing the scene view state param from `src`.
https://vertexvis.atlassian.net/browse/API-1966
> [API-1966] Fix RTE when removing scene view state from src

- packages/viewer/src/components/scene-tree-toolbar/readme.md
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/workers.ts
This disables parsing of depth buffers when running in a Node environment. This should fix a build error when using the SDK in a NextJS app.
https://vertexvis.atlassian.net/browse/API-2048
> [API-2048] Disable parsing of depth buffers in Node environments

- packages/viewer/src/components/viewer-distance-measurement/viewer-distance-measurement.tsx
- packages/viewer/src/components/viewer-measurements/readme.md
- packages/viewer/src/components/viewer-measurements/viewer-measurements.spec.tsx
- packages/viewer/src/components/viewer-measurements/viewer-measurements.tsx
Selection wasn't supported for measurements added as children.
https://vertexvis.atlassian.net/browse/API-2073
> [API-2073] Support selection of measurements added as children

- packages/viewer/src/components/scene-tree-search/scene-tree-search.css
- packages/viewer/src/components/scene-tree-search/scene-tree-search.spec.tsx
- packages/viewer/src/components/scene-tree-search/scene-tree-search.tsx
- packages/viewer/src/components/scene-tree-toolbar/scene-tree-toolbar.css
- packages/viewer/src/components/scene-tree/readme.md
- packages/viewer/src/components/scene-tree/scene-tree.css
- packages/viewer/src/components/scene-tree/scene-tree.tsx
Supports stacking toolbars to create headers and sub-headers in the scene tree. Also tweak the UI for the search bar.
**Example:** Stacking toolbars.
```html
<html>
<body>
<vertex-scene-tree viewer-selector="#viewer">
<vertex-scene-tree-toolbar slot="header">
<vertex-scene-tree-search></vertex-scene-tree-search>
</vertex-scene-tree-toolbar>
<vertex-scene-tree-toolbar slot="header">
<button>A</button>
<button>B</button>
</vertex-scene-tree-toolbar>
<vertex-scene-tree-toolbar slot="footer">
<button>A</button>
<button>B</button>
</vertex-scene-tree-toolbar>
<vertex-scene-tree-toolbar slot="footer">
<button slot="before">A</button>
<div>Footer Text</div>
<button slot="after">A</button>
</vertex-scene-tree-toolbar>
</vertex-scene-tree>
<vertex-viewer id="viewer" …
```
> [API-2083] Scene tree UI tweaks

- packages/viewer/src/lib/interactions/__tests__/mouseInteractions.spec.ts
- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
- packages/viewer/src/lib/interactions/interactionApi.ts
- packages/viewer/src/lib/interactions/mouseInteractions.ts
Adds zoom to cursor behavior for drag interactions. Also makes a small adjustment to the `zoomCamera` method in the `InteractionApi` after noticing some flickering behavior when zoomed in close to the lookAt point.
https://vertexvis.atlassian.net/browse/APP-2577
- Test zoom to cursor with scrolling
- Test zoom to cursor when dragging with `zoom` interaction mode
Zoom to cursor when scrolling
N/A
N/A
> [APP-2577] Zoom to cursor on drag

- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
- packages/viewer/src/lib/interactions/multiPointerInteractionHandler.ts
- packages/viewer/src/lib/interactions/pointerInteractionHandler.ts
- packages/viewer/src/lib/interactions/touchInteractionHandler.ts
Removes `Event.preventDefault()` for most of the viewer interaction events. This caused problems with other UI elements not losing focus, and they don't appear to be needed. Tested on iOS to make sure this wasn't preventing page zooming on mobile.
https://vertexvis.atlassian.net/browse/API-2113
> [API-2113] Remove prevent default for pointer events

- packages/viewer/src/components/viewer-dom-element/viewer-dom-element.spec.tsx
- packages/viewer/src/components/viewer-dom-element/viewer-dom-element.tsx
StencilJS doesn't set attributes if `componentShouldUpdate` returns `false`. This caused problems with occlusion styling via CSS.
https://vertexvis.atlassian.net/browse/PLAT-245
There's a test.
> [PLAT-245] Fix setting occluded attribute

- packages/viewer/src/components/viewer-measurement-precise/viewer-measurement-precise.spec.tsx
- packages/viewer/src/components/viewer-measurement-precise/viewer-measurement-precise.tsx
Fixes a bug where face highlighting would still happen if the `<vertex-viewer-measurement-precise>` element was removed from the DOM. This happened because we did not deregister the interaction handler when the component was removed from the DOM.
https://vertexvis.atlassian.net/browse/PLAT-374
> [PLAT-374] Handle interaction handlers when measurement component added/removed

- packages/geometry/src/plane.ts
- packages/viewer/src/components/viewer-measurement-distance/utils.ts
- packages/viewer/src/lib/types/__tests__/frame.spec.ts
- packages/viewer/src/lib/types/depthBuffer.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/viewport.ts
Fixes an issue where measurement lines were mispositioned if one of its anchors were behind the camera's near plane. Math should be fixed now.
https://vertexvis.atlassian.net/browse/PLAT-19
> [PLAT-19] Fix clipping bug with measurement lines when point behind camera

- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.spec.ts
- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.tsx
- packages/viewer/src/lib/scenes/scene.ts
Include original PointerEvent with node when dispatching selection, expansion, & visibility events on SceneTreeTableCell
> [PLAT-445] Include original PointerEvent with node when dispatching selection, expansion, & visibility events on SceneTreeTableCell

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree-table-cell/readme.md
- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
Updates the retrieval of the ID for a hovered node in the `scene-tree-table-layout` element.
- Test hovering a scene tree cell and changing visibility
N/A
N/A
N/A
> [PLAT-464] Correct retrieval of ID for hovered scene tree cells

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
Adds a test for #286 to ensure that cells properly receive the hovered cell IDs to prevent issues with the way that the event listeners are registered.
- Unit tests
N/A
N/A
N/A
> [PLAT-464] Add test for cell hover

- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
- packages/viewer/src/lib/interactions/interactionApi.ts
- packages/viewer/src/lib/interactions/mouseInteractions.ts
Makes a couple updates to the twist (Alt+Shift) interaction:
- Moves to using client X/Y instead of screen X/Y. This corrects some odd behavior when the viewport is scaled, since the `twistCamera` method uses the center of the viewport as a reference point for angles.
- Adds a check when ending an interaction to set the `currentInteraction` back to undefined in the case of twist to prevent the current case where twist applies to the interaction immediately following it 
- Test scaling a browser window to 50% -- twist should work as expected
- Test performing a twist, then a second interaction with no modifier keys -- this should default back to the primary interaction
N/A
Twist
N/A
> [PLAT-175] Twist interaction updates

- packages/html-templates/package.json
Corrects an issue where the Stencil dev server was unable to find the `@vertexvis/html-templates` package. Stencil was looking for the `browser` bundle, which the package indicates that it has, though it is not actually generated.
- Test running `yarn start` from the viewer package
- The scene tree should load properly
N/A
N/A
N/A
> [PLAT-550] Fix html-templates package locally

- packages/viewer/src/components/viewer/viewer.css
- packages/viewer/src/lib/stream/__tests__/stream.spec.ts
- packages/viewer/src/lib/stream/stream.ts
Fixes a couple bugs during testing with Connect+ where the viewer would fail to connect because the dimensions were `(0,0)`. We now set a min width/height on the viewer of 1px and check if the args to update stream have empty dimensions.
https://vertexvis.atlassian.net/browse/PLAT-385
> [PLAT-385] Set min size for viewer

- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/stream/state.ts
This fixes an issue where the viewer would throw an exception if the session ID was not passed back from FSS, which happens when a client ID is not set. Making this property optional, to reflect the behavior of FSS.
https://vertexvis.atlassian.net/browse/PLAT-385
> [PLAT-385] Make session ID an optional stream property

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.tsx
- packages/viewer/src/interfaces.d.ts
- packages/viewer/src/lib/mappers/material.ts
- packages/viewer/src/lib/stream/stream.ts
Fixes an issue where the scene tree becomes unresponsive if you remove and add a new tree to the DOM. This was happening because STS only allows a single subscription per scene view, and we were not terminating the connection of the tree that was removed.
https://vertexvis.atlassian.net/browse/PLAT-581
> [PLAT-581] Scene tree connection fixes

- packages/geometry/src/__tests__/euler.test.ts
- packages/geometry/src/__tests__/matrix4.test.ts
- packages/geometry/src/__tests__/quaternion.test.ts
- packages/geometry/src/matrix4.ts
- packages/viewer/src/components/viewer-view-cube/viewer-view-cube-components.tsx
- packages/viewer/src/components/viewer-view-cube/viewer-view-cube.tsx
- packages/viewer/src/lib/types/standardView.ts
`makeRotation` was returning a row-major matrix. Our Matrix4 expects column-major.
https://vertexvis.atlassian.net/browse/PLAT-629
> [PLAT-629] Fix makeRotation returning incorrect row-major matrix

- packages/viewer/src/components/viewer-markup/viewer-markup.tsx
Adds a watch for the `freeformTemplateId` property on the viewer markup element. This corrects an issue on the connect-app side with the updates to modify markup color where the markup tool would not pick up the newly modified template.
- Test updating the freeform markup template ID on a `<viewer-markup>` element
- freeform markup ID on the nested `<viewer-markup-tool>` element should be updated
N/A
N/A
N/A
> [PLAT-300] Add watch for freeform template

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/interactions/__tests__/flyToPartKeyInteraction.spec.ts
- packages/viewer/src/lib/interactions/__tests__/flyToPositionKeyInteraction.spec.ts
- packages/viewer/src/lib/interactions/flyToPartKeyInteraction.ts
- packages/viewer/src/lib/interactions/flyToPositionKeyInteraction.ts
Adds support for a "Fly to Position" keybind (`Alt` + `Shift`), and modifies the existing "Fly to Part" keybind (`Alt` + !`Shift`).
https://user-images.githubusercontent.com/5252480/147977038-6bc78afa-646a-4cb0-8958-8550157f2ef7.mov
- Test fly to part (`Alt` + Click)
- Test fly to position (`Alt` + `Shift` + Click)
N/A
Fly to part
N/A
> [PLAT-287] Add lookAt shortcut

- packages/viewer/src/components/scene-tree/lib/viewer-ops.ts
We want to append to the current scene-tree by default when using multi-selection. 
Try to multi-select.
None
Multi-selection
None
> [PLAT-689] Append by default with range selection

- packages/viewer/src/lib/types/__tests__/featureMap.spec.ts
- packages/viewer/src/lib/types/entities.ts
- packages/viewer/src/lib/types/featureMap.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/index.ts
- packages/viewer/src/testing/fixtures.ts
Adds a method `FeatureMap.getEntityType` to query the feature map for the type of entity at a given point.
https://vertexvis.atlassian.net/browse/PLAT-542
> [PLAT-542] Add method to query entity types in feature map

- packages/viewer/src/components/viewer-markup-arrow/viewer-markup-arrow.tsx
- packages/viewer/src/components/viewer-markup-circle/viewer-markup-circle.tsx
- packages/viewer/src/components/viewer-markup-freeform.tsx/viewer-markup-freeform.tsx
Updates the markup elements to continue to render the `create-overlay` div when in create mode, regardless of whether the drawing has started. This corrects an issue where starting a markup on mobile with a single touch point, then accidentally or intentionally touching the screen a second time (due to how the stylus is held, hand resting on the screen, etc) would cause the model to rotate and the markup to behave unexpectedly.
- Test markup on mobile
- Test markup on desktop
- Test starting a markup on mobile with a single touch, then touching the screen a second time during the drawing
N/A
Markup
N/A
> [PLAT-763] Maintain create overlay while drawing

- packages/viewer/src/components/scene-tree/scene-tree.css
In Safari, the text in the scene tree was selectable and had the text selection cursor.  After this PR, the behavior in Safari matches other browsers.
Before:
After:
Look at the scene tree in Safari
None
Scene tree
None
> [PLAT-688] Scene tree cursor in Safari

- scripts/publish_canary.sh
This fixes an issue where resolution of a canary's package dependencies would not resolve to the exact canary version. This would cause problems when a canary version was released, but projects still depended on canary.
For example, the following:
```
├─ @vertexvis/viewer-react@0.12.0-canary.59
│  └─ @vertexvis/viewer@^0.12.0-canary.59
├─ @vertexvis/viewer@0.12.0
│  ├─ @improbable-eng/grpc-web@^0.15.0
│  ├─ @stencil/core@^2.12.1
│  ├─ @types/classnames@^2.3.1
│  ├─ @vertexvis/frame-streaming-protos@^0.6.16
│  ├─ @vertexvis/geometry@0.12.0
│  ├─ @vertexvis/html-templates@0.12.0
│  ├─ @vertexvis/scene-tree-protos@^0.1.11
│  ├─ @vertexvis/scene-view-protos@^0.1.7
│  ├─ @vertexvis/stream-api@0.12.0
│  ├─ @vertexvis/utils@0.12.0
│  ├─ @vertexvis/web-workers@^0.1.0
│  ├─ camel-case@^4.1.2
│  ├─ …
```
> [PLAT-900] Use exact versions of dependencies for canary releases

- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
Ran into issues upgrading the Xamarin SDK to latest due to attempts to access local storage to retrieve a device ID. Xamarin will set this value prior to loading a model so it avoids the lookup, but this constructor call still attempts a lookup before the ID can be set. Didn't appear to be any need for that constructor lookup, so this PR removes it.
- Verify the device ID in local storage still persists and is used as expected
N/A
Device ID lookups
N/A
> [PLAT-993] Remove getDeviceId call from viewer constructor

- packages/viewer/src/components/viewer-measurement-distance/utils.ts
- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.tsx
- packages/viewer/src/components/viewer-measurement-overlays/viewer-measurement-overlays-components.tsx
Measurement overlay lines would appear mispositioned if one of its anchors was positioned behind the camera. Now the lines are clipped to the screen plane.
https://vertexvis.atlassian.net/browse/PLAT-1009
> [PLAT-1009] Fix measurement overlay lines

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/scenes/__tests__/queries.spec.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/queries.ts
- packages/viewer/src/lib/scenes/scene.ts
Adds a `withPoint` query that takes a point from a tap event to avoid needing to perform an explicit hit request for hit-based operations.
- Test the `withPoint` query
- Particularly on scaled up viewports to verify it operates on the correct item
N/A
N/A
N/A
> [PLAT-895] Add withPoint query

- packages/viewer/src/components/viewer/viewer.tsx
While testing support for local development in PowerBI, the SDK was throwing an error because iframes don't have access to local storage when loading a local file. This will log a warning if trying to retrieve/save the device ID.
https://vertexvis.atlassian.net/browse/PLAT-1131
> [PLAT-1131] Trivial support for Web SDK in iframes

- packages/viewer/src/lib/scenes/__tests__/camera.spec.ts
- packages/viewer/src/lib/types/__tests__/depthBuffer.spec.ts
- packages/viewer/src/lib/types/clippingPlanes.ts
Corrects the calculation of the `near` and `far` clipping plane values to match those computed in RCL.
Also created https://vertexvis.atlassian.net/browse/PLAT-1187 to discuss/address this issue in the future.
- Test rotate around tap when zoomed in close to a part
N/A
N/A
N/A
> [PLAT-1151] Fix rotate around tap

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/scenes/scene.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/frameCamera.ts
Adds an `isOrthographic` and `isPerspective` method to the `FrameCameraBase` to avoid having to do `instanceof` checks. Additionally, this corrects an issue where the connect-app was unable to use the helpers for checking the type of a camera.
- Test changing between perspective and orthographic cameras
N/A
Changing between orthographic and perspective cameras
N/A
> [PLAT-267] Move camera type checks

- packages/viewer/src/lib/interactions/__tests__/flyToPositionKeyInteraction.spec.ts
- packages/viewer/src/lib/interactions/flyToPositionKeyInteraction.ts
Corrects the behavior of the look at position keybinding (Alt/Option + Shift + Click) in orthographic mode to properly send an orthographic camera.
- Test look at position in perspective mode
- Test look at position in orthographic mode
N/A
Look at position in perspective mode
N/A
> [PLAT-1266] Fix look at position in orthographic mode

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.spec.tsx
- packages/viewer/src/components/viewer-pin-label/readme.md
- packages/viewer/src/components/viewer-pin-label/utils.ts
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.css
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.spec.tsx
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.tsx
Makes a handful of improvements to the text pin label behavior:
- Dragging the label is now based off relative difference from the `pointerdown` event versus the label anchor, and will stay under the cursor when dragging from somewhere in the middle of the label
- Styles have been updated to be more consistent between the "readonly" state and the focused state
- The `input` element has been changed to a `textarea` along with auto resizing behavior to support multiline text content
- A max width + height have been added
- The labels are now constrained to the width and height of the viewer such that typing content will not go off-screen and shift the location of the overlay (and shift the 3D pin anchors)
- A `labelFocused` and a `labelBlurred` event have been added
- Test text pins …
> [PLAT-1307] Pin label state improvements

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-dom-element/readme.md
- packages/viewer/src/components/viewer-dom-element/viewer-dom-element.spec.tsx
- packages/viewer/src/components/viewer-dom-element/viewer-dom-element.tsx
- packages/viewer/src/components/viewer-dom-group/readme.md
- packages/viewer/src/components/viewer-dom-group/viewer-dom-group.spec.tsx
- packages/viewer/src/components/viewer-dom-group/viewer-dom-group.tsx
- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.css
- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.tsx
- packages/viewer/src/lib/pins/__tests__/interactions.spec.ts
- packages/viewer/src/lib/pins/controller.ts
- packages/viewer/src/lib/pins/interactions.ts
These changes introduce moving the world position on the pin. You can drag the anchor for a text label, as well as a regular simple pin while in edit mode. 
- Test that you can drag a text pin anchor and that it's always positioned on the model
- Verify you can do the same with a simple pin
> [PLAT-1290] Support for draggable pins

- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/scene-tree/lib/errors.ts
- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.tsx
These changes introduce some improvements to the messaging & retry-ability of a non loaded scene tree. Below are two things I think might be happening, both of them are error states, but the second could be a symptom of the first. Since this has been historically hard to reproduce, I am proposing to add custom error messages in either of these two conditions. 
1. Upon investigation, I found that when using the `viewer-selector`, the scene tree does not try to look up the viewer again in the dom. A potential longer term fix here could be to check if the viewer-selector is not null, and the viewer _is_ null, and re-assign that on a post-render event. For now I'd prefer to gather additional information, as well as display to the user what's really happening. This case specifically happens …
> [PLAT-1035] Improved Scene Tree error states

- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.tsx
These changes introduce a resolution to a long standing bug. Here were my steps to reproduce the issue, although it was still intermittent:
1. In a developer console in Chrome, set the CPU slowdown to 4x or 6x. 
2. Open the Scene tree (Ideally if you're on a fast network)
3. The scene tree intermittently does not load. 
The nature of this bug is that the scene tree controller is dispatching updates from the network responses, prior to the scene tree component rendering for the first time. The first time render is where we ensure that the scene-tree-layout is defined:
```ts
public componentWillRender(): void {
this.ensureLayoutDefined(); // <-- here
...
}
```
The `updateLayoutElements` only gets called on a state change, and within that function is the following:
```ts
if (layout != null) …
```
> [PLAT-1035] Load layout on render

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree/lib/viewer-ops.ts
- packages/viewer/src/components/scene-tree/readme.md
- packages/viewer/src/components/scene-tree/scene-tree.tsx
We want the ability to select all of the matches for a given metadata search. 
Tested with connect-app
None
None
None
> [PLAT-645] Select scene tree search results

- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
Corrects an issue with initializing the transform widget with a `position`, where the current position would not be correctly initialized. Also corrects an issue where some errors were being logged unnecessarily when changing the position.
- Test loading the widget from connect-app
N/A
N/A
N/A
> [PLAT-1193] Correct transform widget first time load w/ a position

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-transform-widget/readme.md
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.spec.tsx
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
Introduces a new event to be emitted each time the position of the widget changes.
```ts
const widget = document.getElementById('widget');
widget.addEventListener('positionChanged', (e) => {
console.log('position: ', e.detail);
})
```
> [PLAT-1528] Emit Position Changing for the transform widget

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-transform-widget/readme.md
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.spec.tsx
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
- packages/viewer/src/lib/transforms/controller.ts
These changes introduce two new events. Events emitted when the widget delta position changes, as well as an event for when the widget has begin an interaction.
> [PLAT-1528] Adding events for delta changed and interaction started

- packages/viewer/src/components/viewer-measurement-distance/__tests__/hitTest.spec.ts
- packages/viewer/src/lib/types/__tests__/depthBuffer.spec.ts
- packages/viewer/src/lib/types/__tests__/viewport.spec.ts
- packages/viewer/src/lib/types/depthBuffer.ts
Corrects the math for orthographic depth calculation. Previously, this math was attempting to account for a ray generated at `z = 0.5`, which is no longer generated by the `Viewport.transformPointToOrthographicRay` method. Additionally, this PR updates a couple tests that should have caught this bug (in packages/viewer/src/lib/types/__tests__/depthBuffer.spec.ts), as they were not using the correct ray generation/world point generation methods.
- Test rotate around tap point in orthographic mode
- Unit tests
N/A
N/A
N/A
> [PLAT-1560] Correct orthographic depth

- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/colorMaterial.ts
Set opacity on default materials to 255
Set glossiness, ie specular exponent, to 50 (is this too glossy?)
Verified in a test app
Will need to be picked up by Connect+ 
[Ticket](https://vertexvis.atlassian.net/browse/PLAT-1570)
> [PLAT-1570] -- opaque selection material

- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.tsx
If the pt-to-pt measurement component is removed mid-interaction, the interaction was not being disposed. This causes any `editEnd` events to be fired the next time a user performs a mouse interaction, and was causing state to get updated in Connect.
https://vertexvis.atlassian.net/browse/PLAT-1477
> [PLAT-1477] Dispose of measurement interaction when component removed

- packages/viewer/package.json
This fixes the path that should be used for the typings definition file.
https://vertexvis.atlassian.net/browse/PLAT-1683
> [PLAT-1683] Fix path to typings definition file

- packages/viewer/src/lib/stream/__tests__/stream.spec.ts
- packages/viewer/src/lib/stream/stream.ts
The repro steps are defined in the ticket [PLAT-1724](https://vertexvis.atlassian.net/browse/PLAT-1724).
This can be reproduced any time that the client side stream model gets an updated dimension while not in the `connected` state. This is easily reproducible by resizing the viewer window, while the frame stream was reconnecting. 
Prior to these changes, the method `updateDimensions` was only invoked when the stream was in a connecting state:
```ts
this.dimensions = fields.dimensions;
this.ifState('connected', () => {
this.updateDimensions({ dimensions: this.dimensions });
});
```
This led to the dimensions in the `ViewerStream` to be mismatched with what the server side frame stream was reporting. 
The change here, detects this situation, and updates the dimensions correctly.
> [PLAT-1724] Dimensions should be updated to whatever was set in the client after connection is successful

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
Corrects an issue with `getRowAtClientY` when the header changes and does not trigger a table resize.
- Test the scene tree context menu in Connect on initial load with columns (see https://vertexvis.atlassian.net/browse/PLAT-1785 for specific repro steps)
N/A
Layout offset when the header resizes
N/A
> [PLAT-1785] Update layout offset when header changes

- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.tsx
This should fix the toggling of partial visibility. Before nothing would happen because the state wasn't being checked.
https://vertexvis.atlassian.net/browse/PLAT-1786
> [PLAT-1786] Fix toggle of partial visibility

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/__tests__/operations.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/operations.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
Adds support for a `clearTransforms(...)` operation, which optionally takes a `cascade` flag indicating whether the operation should clear all transform overrides of child elements of those that match the provided query. (note: this is the only way the `all()` query will work for clearing any transforms lower than the root node).
- Test performing a transform using `transform(...)` alteration, and then performing a `clearTransforms()` alteration for the same node
- The transform override should be removed
- Test performing a transform of an assembly item and a child of that assembly using the `transform(...)` alteration, then performing a `clearTransforms()` alteration for the assembly
- Both the assembly and child transforms should be removed
- Test performing a transform of an assembly …
> [PLAT-1533] Support clear transform scene item operations

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
Adds support for changing the values of `cameraControls` and `keyboardControls` on the viewer after it has loaded.
- Test loading a model in the viewer, then changing `cameraControls` to false, then back to true
- Test loading a model in the viewer, then changing `keyboardControls` to false, then back to true
N/A
Camera and keyboard controls on initial load
N/A
> [PLAT-1799] Allow toggling of cameraControls and keyboardControls

- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.spec.tsx
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.spec.tsx
- packages/viewer/src/components/viewer-view-cube/viewer-view-cube.spec.tsx
- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/rendering/__tests__/canvas.spec.ts
- packages/viewer/src/lib/rendering/canvas.ts
- packages/viewer/src/testing/fixtures.ts
This change adds a `drawPredicate` to the `canvasRenderer` in the viewer to determine whether frames should be drawn to the canvas after completing the `loadImageBytes` call. This corrects a race condition between smaller and larger frames that come in at close to identical times, such as when all parts are hidden in the viewer.
- Load a (large-ish) model, and zoom in such that the image takes up the entire viewer (also, the larger the viewer window the more reproducible this bug is), then toggle visibility from the scene tree repeatedly
- The image should always update with empty frames when the root node is hidden
N/A
Frame drawing behavior
N/A
> [PLAT-1624] Skip drawing older frames to the canvas

- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
When dragging the transform widget outside of the viewer, the sidebar and header text became selected.  Further, if a Windows user dragged the transform widget, interacted with the view cube, and then attempted to drag the transform widget again, the widget continued to move after lifting the mouse button.
Interact with the transform widget.  Verify that text is not selected when the widget is dragged outside of the viewer and the widget continues to work after interacting with the view cube.
None
Dragging the transform widget
None
> [PLAT-1773] preventDefault when dragging transform widget

- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/stream/__tests__/stream.spec.ts
- packages/viewer/src/lib/stream/stream.ts
- packages/viewer/src/testing/viewer.ts
Changes the behavior of the sync of dimensions of the `vertex-viewer` element and the underlying stream. Previously, after each frame request we would send an `updateDimensions` request if the stream dimensions did not match the frame dimensions to correct an issue where the dimensions were out of sync on initial load. When interacting, this would cause an `updateDimensions` to be sent after every frame, as the frame that came back would have a reduced size that did not match the viewer/stream's expected dimensions.
This change updates the resize handling to check whether the stream is actually in the `connected` state before attempting to update the stream dimensions, then in the `handleConnected` callback, we'll always send an update to the stream to verify that we have the same …
> [PLAT-1792] Prevent additional updateDimensions requests

- packages/viewer/src/components/viewer-dom-renderer/viewer-dom-renderer.spec.tsx
- packages/viewer/src/components/viewer-dom-renderer/viewer-dom-renderer.tsx
- packages/viewer/src/components/viewer-pin-tool/viewer-pin-tool.spec.tsx
- packages/viewer/src/components/viewer-pin-tool/viewer-pin-tool.tsx
Fixes an issue where the `projectionViewMatrix` of the `vertex-viewer-pin-tool` element and the `camera` of the underlying `vertex-viewer-dom-renderer` would not properly be populated when added as a child to a `vertex-viewer` element after an initial load. This would then result in text-pins being improperly positioned, and would cause them not to appear until the camera was rotated.
- Programmatically add a `vertex-viewer-pin-tool` as a child of a `vertex-viewer` element after a button click in edit + text-pin mode
- Verify that text pins appear when a click occurs, and that the leader line + anchor point visually appear in the correct location
N/A
N/A
N/A
> [PLAT-2009] Fix initial pin-tool load behavior

- scripts/publish_canary.sh
Adds a `and contains("canary")` condition to the `publish_canary` script. This resolves an issue where packages published under the `testing` tag could be picked up as the latest canary version due to appearing lower in the `npm view` list.
- Verify this PR publishes a new canary version with the proper `.canary` text in the version name
N/A
Canary releases
N/A
> [PLAT-1814] Add filter for canary in version name

- packages/viewer/src/lib/interactions/__tests__/mouseInteractions.spec.ts
- packages/viewer/src/lib/interactions/mouseInteractions.ts
Updates the `TwistInteraction` to leverage `offsetX` and `offsetY` so the points are relative to the viewer rather than the window.
- Render an element that reduces the size of the viewer to 50% of the window and verify that the center point of the Twist interaction is the center of the viewer
N/A
Twist interactions
N/A
> [PLAT-1806] Update Twist to use offset values

- packages/viewer/src/lib/interactions/__tests__/mouseInteractions.spec.ts
- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
- packages/viewer/src/lib/interactions/mouseInteractions.ts
Fixes an issue where the `offsetX` and `offsetY` values were being computed for non-viewer elements.
- Test the twist gesture when moving the mouse between an element on the side and the viewer
N/A
Mouse interactions
N/A
> [PLAT-1806] Fix offset when off canvas

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
We want to support the ability to apply a subset of a SceneViewState's features to the current scene, instead of the full SceneViewState.
Verify that a user can apply a partial SceneViewState
None
Viewing snapshots
None
> [PLAT-2189] Apply partial SceneViewState

- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.css
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.tsx
- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/interactions/__tests__/mouseInteractionHandler.spec.ts
- packages/viewer/src/lib/interactions/baseInteractionHandler.ts
Makes a small change to always instantiate the `TapInteractionHandler`, regardless of the `cameraControls` flag, as this interaction handler only emits events rather than interacting with the camera. This allows for handling of `tap` events when performing a box-query.
Additionally, this PR makes a few small changes as polish for the removal of the box-selection feature flag:
- The rotate camera interaction is now mapped to the Middle or Auxiliary mouse button (`4`), and will use either `rotate-point` or `rotate` depending on the last one used as a primary interaction
- The styling of the box-query outline + fill has been adjusted slightly to show the fill behind the border of the `inclusive` query
- Verify that `tap` events are emitted when clicking with the …
> [PLAT-2273] Allow tap interactions without camera controls

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/interactions/__tests__/mouseInteractions.spec.ts
- packages/viewer/src/lib/rendering/matrices.ts
- packages/viewer/src/lib/transforms/drawable.ts
Fixes some bugs reported in Sonar that started showing up with #455 and failed the checks in #456.
- Verify viewer behavior when providing a `src` attribute on component load
N/A
Viewer behavior when initially loading from a `src` attribute
N/A
> [PLAT-2273] Fix bugs from Sonar report

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/scenes/__tests__/camera.spec.ts
- packages/viewer/src/lib/scenes/camera.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/frameCamera.ts
- yarn.lock
Introduces support for fovY on a perspective camera. The main plumbing was here for this, was just not mapped via protos. 
Verify that the fovY can be passed into perspective cameras. Valid ranges are float values between 1 & 179, which are enforced server-side
https://github.com/Vertexvis/frame-streaming-service/pull/308
> [PLAT-2334] FovY Support for Perspective Cameras

- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.tsx
When no developer provided metadata keys are present, we log out a warning, and default the value to the name (Consistent with the search experience)
Initiate a viewer without metadata keys, apply a search filter, and try to do a selectFilteredItems. Previously this would fail, but with the [recent changes in metadata service](https://github.com/Vertexvis/metadata-service/pull/115), as well as this warning, the experience should be obvious.
https://github.com/Vertexvis/metadata-service/pull/115
> [PLAT-2222] Add warning when no keys are present, default to name - same as search

- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.tsx
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.spec.tsx
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.tsx
- packages/viewer/src/components/viewer-pin-tool/readme.md
- packages/viewer/src/components/viewer-pin-tool/utils.ts
- packages/viewer/src/components/viewer-pin-tool/viewer-pin-tool.css
- packages/viewer/src/components/viewer-pin-tool/viewer-pin-tool.tsx
- packages/viewer/src/lib/pins/interactions.ts
- packages/viewer/src/lib/pins/model.ts
Improvements to text markup, specifically:
- Auto-focuses on new pins when the pin is created such that the user can start typing right away
- Includes a visible label line when the pin is created instead of the label touching the anchor. The label is always positioned towards the center of the screen relative to the anchor point and should be present on the screen.
- Prevents typing 'f' in the pin label from triggering a fit all
- Pressing "Enter" now submits the label text 
- Pressing either "Shift+Enter" or "Control/Command+Enter" now adds a new text line in the existing label
Verify the items listed above
None
Text markup
None
> [PLAT-2131] Text pins improvements

- packages/viewer/src/components/viewer-pin-label/readme.md
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.css
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.spec.tsx
- packages/viewer/src/components/viewer-pin-label/viewer-pin-label.tsx
- packages/viewer/src/lib/pins/interactions.ts
When moving a text markup label around the screen, the text in other labels was being highlighted.  Further, it was requested that we reduced the extra space on the right side of the label.
Verify that moving a text markup label no longer highlights the text in other labels
None
Text markup
None
> [PLAT-2474] Prevent highlighting text in label

- packages/viewer/src/components/scene-tree/lib/__tests__/controller.spec.ts
- packages/viewer/src/components/scene-tree/lib/controller.ts
These changes introduce a retry on the subscription call when the handshake timeout fails within the allotted timeout. This is to improve resiliency for first time connections, and attempts so establish a handshake more consistently.
> [PLAT-2258] Subscription Retries

- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.spec.tsx
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.tsx
- packages/viewer/src/lib/volume-intersection/__tests__/controller.spec.ts
- packages/viewer/src/lib/volume-intersection/controller.ts
Adds an `executeAborted` event dispatcher to the volume intersection controller in the case that we receive too many items that match the query. This can then be handled on the consumer-side rather than logging an error for the expected behavior.
- Verify that there is no console.error log for queries that are aborted
- Verify the listener registered using the `onExecuteAborted` method is called with the error
N/A
Volume intersection query error handling
N/A
> [PLAT-2437] Add executeAborted event for box-query tool

- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.spec.tsx
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
Corrects an issue where the `startingTransform` was not set when loading the transform widget with a starting position.
- Verify the transform widget works as expected when initialized with a position
N/A
N/A
N/A
> [PLAT-2244] Correct transform widget position initialization

- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/scene-tree/lib/errors.ts
- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
Adds error mapping for the `Aborted` status code to display a separate message from the `Unknown` status code catch all.
- Verify that attempting to load a tree that has been blocked results in the `Aborted` request messaging
N/A
N/A
N/A
> [PLAT-2825] Add Aborted status code mapping

- package.json
After #479 moved some of the types around, the `nextVersionBump` needs to be moved to `minor` to reflect that the typings have moved.
- Verify the canary release is for the next minor version (0.17.0)
N/A
N/A
N/A
> [PLAT-2825] Update to minor version bump

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/types/__tests__/frame.spec.ts
- packages/viewer/src/lib/types/frame.ts
These changes add a unique identifier on a frame. We then check the ID of the frame instead of doing an object compare on these frames. This solves the problem of not updating the frame on a reconnect when the frames are in fact equal, but have mismatching correlation IDs which resulted in unnecessarily discarding of frames. 
- Open a scene in the viewer
- Interact with it for a while to increase the sequence count on a frame (Rotate for 10-15 seconds)
- Let the viewer sit for a minute or so until you identify that a websocket reconnection has occurred (This can be observed in the network tab when you see a new connection to the web socket)
- Verify the scene you have open is immediately able to be interacted with, and is not stale.
> [PLAT-2862] Using a unique ID for comparing frames, since the copy may contain additional correlation IDs

- packages/viewer/package.json
- packages/viewer/stencil.config.ts
- packages/viewer/tsconfig.json
- scripts/generate_docs.sh
- yarn.lock
Adds support for generation of source maps for the @vertexvis/viewer package. This allows consumers to generate their bundles with source maps.
https://vertexvis.atlassian.net/browse/PLAT-2556
> [PLAT-2556] Support generation of source maps for viewer

- packages/viewer/src/components/viewer-hit-result-indicator/lib/__tests__/indicator.spec.ts
- packages/viewer/src/components/viewer-transform-widget/__tests__/widget.spec.ts
- packages/viewer/src/lib/transforms/drawable.ts
- packages/viewer/src/testing/webgl.ts
Fixes an issue with our components that leverage WebGL where the buffers created were not large enough for draw calls. Looking at the internals of the `regl-shape` library, this appears to be related to the typed arrays there being created using the length of the provided `pointsArray`, and there is a specific callout in the README around ensuring the `count` provided is less than half the length of the provided `pointsArray` (which we used exactly half). The specific value of `4` appears to relate to the fill colors, as providing a value of `2` results in a loss of fill colors in certain scenarios, where a value of `3` results in the same warning (in addition to other issues related to the odd-length array).
Specific warning:
```
GL_INVALID_OPERATION: Vertex buffer is not big enough for …
```
> [PLAT-2787] Fix WebGL warnings

- packages/viewer/src/components/viewer-hit-result-indicator/lib/__tests__/dom.spec.ts
- packages/viewer/src/components/viewer-hit-result-indicator/lib/dom.ts
- packages/viewer/src/components/viewer-hit-result-indicator/viewer-hit-result-indicator.css
- packages/viewer/src/components/viewer-hit-result-indicator/viewer-hit-result-indicator.tsx
- packages/viewer/src/components/viewer-transform-widget/__tests__/widget.spec.ts
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
- packages/viewer/src/components/viewer-transform-widget/widget.ts
Updates the `<vertex-viewer-transform-widget>` element to support having its disabled state updated prior to initialization of the widget by providing it when the widget is initialized. Additionally, this PR updates the CSS definitions for the `<vertex-viewer-hit-result-indicator>` element to not include single quotes, and updates the `parseCssColorValue` method to remove single quotes when retrieving a property value.
- Verify that the transform widget does not log errors when the disabled states change prior to initialization
- Verify that the transform widget still properly updates disabled states after initialization
- Verify that the hit result indicator has a default color of `#0099cc`
N/A
Transform widget disabled states
N/A
> [PLAT-2919] Update hit indicator default colors and transform widget disabled state initialization

- packages/viewer/src/components/viewer-transform-widget/__tests__/widget.spec.ts
- packages/viewer/src/components/viewer-transform-widget/readme.md
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.css
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
- packages/viewer/src/components/viewer-transform-widget/widget.ts
- packages/viewer/src/lib/transforms/drawable.ts
- packages/viewer/src/lib/transforms/line.ts
- packages/viewer/src/lib/transforms/mesh.ts
- packages/viewer/src/lib/webgl/regl-component.ts
These changes are to update the disabled state of the transform widget. Instead of specifying a color, the disabled widget shows an opacity to maintain the color to denote which axis are disabled. These changes are being made to make the disabled state a better experience for users who have reported that the disabled state is not obvious. 
Verify the opacity is shown on a disabled axis by making the opacity lighter for the transform widget.
> [PLAT-2949] Opacity on Disabled Transform State

- packages/stream-api/package.json
- packages/stream-api/src/testing/fixtures/requests.ts
- packages/viewer/package.json
- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/types/displayListSummary.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/index.ts
- packages/viewer/src/testing/fixtures.ts
- yarn.lock
Wires up the `DisplayListSummary` introduced with version `0.10.0` of the frame-streaming-protos.
- Verify that frames emitted through the `receiveFrame` or `drawFrame` methods have a `displayListSummary` field on the `scene`
N/A
N/A
N/A
> [PLAT-2346] Wire up display list summary

- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/index.ts
- packages/viewer/src/lib/types/sceneViewSummary.ts
Renaming the summary added with #499 from `displayListSummary` to `sceneViewSummary` to avoid using the term `DisplayList` in the SDK context.
- Verify that the `displayListSummary` is remapped to a `sceneViewSummary` on the frame
N/A
Display list summary
N/A
> [PLAT-2346] Rename displayListSummary

- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.spec.tsx
- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.tsx
We want to handle long presses in the scene tree on mobile separately from single tap events. As a result, long pressing on a node in the scene tree will no longer select the item.
Verify that long pressing on a node in the scene tree does not select the item.
None
Long presses in the scene tree
None
> [PLAT-1181] Handle long press in the scene tree

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/types/__tests__/sceneViewSummary.spec.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/sceneViewSummary.ts
Adds support for ignoring "invalid" display list summaries on incoming frames, instead copying the previous frame's summary. This corrects a case on reconnects where the new FrameStream had not received a summary, and would send an empty set of visible/selected items rather than the current counts/bounds.
- Verify that the `sceneViewSummary` property on the `viewer.frame` maintains its state across reconnects
- Verify that the `sceneViewSummary` property is updated after a reconnect if a selection/visibility change is made
N/A
N/A
https://github.com/Vertexvis/frame-streaming-service/pull/339
> [PLAT-3012] Ignore invalid summaries on incoming frames

- packages/viewer/src/components/scene-tree/lib/__tests__/controller.spec.ts
- packages/viewer/src/components/scene-tree/lib/controller.ts
We were calling _dispose_ on the scene tree connection twice, which was throwing errors in scene-tree.  Therefore, this PR removes the duplicate call.
Verify that the scene tree works as expected. Particularly, verify that scene view states can be applied to an instance of the scene tree.
None
Scene-tree connection
None
> [PLAT-2763] Only dispose scene-tree subscription once

- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
Adds a `@Watch` for specific `row` properties (`rows`, `totalRows`, and `rowHeight`) that impact the rendering of the viewport start/end indices. This is normally done as a part of `componentWillRender`, but some of the changes to these values appear to not have been triggering a rerender. This was resulting in a potential spinner condition where the viewport indices never correctly got updated, and resulted in the first row not being rendered. This appears to have been specifically an issue with the `viewer-react` components, as I did not see this purely using the SDK elements.
- Verify that the spinner does not appear in Connect
N/A
N/A
N/A
> [PLAT-3145] Add Watch to specific row props

- packages/viewer/src/components/scene-tree/lib/controller.ts
Fixes an accidental leftover testing change with #516.
- Verify the scene-tree reconnects every 4 minutes
N/A
N/A
N/A
> [PLAT-3145] Fix unintentional idle reconnect reduction

- packages/viewer/src/components/scene-tree/lib/controller.ts
Updates the initial setup of the scene-tree controller to wait for the `subscribe()` call prior to attempting to fetch the first page. This appears to have been causing an issue where the `ListChange` sent by STS was getting lost (no `listener` available to send the change to) and the initial `GetTree` was receiving an empty list.
- Verify that the tree does not appear blank on initial load
- Verify that the tree spinner properly resolves on initial load
N/A
Tree connections
N/A
> [PLAT-3145] Subscribe before first GetTree

- packages/viewer/src/components/scene-tree/lib/__tests__/controller.spec.ts
- packages/viewer/src/components/scene-tree/lib/controller.ts
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.spec.tsx
- packages/viewer/src/components/viewer-transform-widget/viewer-transform-widget.tsx
- packages/viewer/src/testing/grpc.ts
- Fixes an issue with the transform widget where it could become "disconnected" from a part if the handles were double-clicked
- Fixes an issue with the scene-tree where the response to a `ListChange` would not always attempt to fetch the first page of the tree
- Fixes an issue where a second subscription would be set up (in response to a handshake timeout) if the handshake was received on a subscription prior to the `GetTree` response
Transform widget behavior before:
https://github.com/Vertexvis/vertex-web-sdk/assets/5252480/3d847cdb-f3cd-4301-8729-46de9025235f
Transform widget behavior after:
https://github.com/Vertexvis/vertex-web-sdk/assets/5252480/93f63385-4cb4-444b-ae13-b991253e0407
- Verify that double-clicking the handle on a transform widget then performing a transform works as …
> [PLAT-3131] Fix transform widget disconnect + more scene-tree spinners

- README.md
- packages/viewer-vue/.eslintrc.js
- packages/viewer-vue/LICENSE
- packages/viewer-vue/package.json
- packages/viewer-vue/rollup.config.js
- packages/viewer-vue/src/README.md
- packages/viewer-vue/src/index.ts
- packages/viewer-vue/src/lib/plugin.ts
- packages/viewer-vue/tsconfig.json
- packages/viewer/package.json
- packages/viewer/stencil.config.ts
- tsconfig.docs.json
- yarn.lock
Adds a new `@vertexvis/viewer-vue` package that contains Vue bindings for the `@vertexvis/viewer` package.
- Create a simple Vue application (see https://vuejs.org/guide/quick-start.html) and follow the instructions in the `README` to add a viewer - verify this process works as expected
N/A
N/A
N/A
> [PLAT-3209] Add Vue bindings

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/components/viewer/utils.ts
- packages/viewer/src/components/viewer/viewer.css
- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/interfaces.d.ts
- packages/viewer/src/lib/mappers/__tests__/streamAttributes.spec.ts
- packages/viewer/src/lib/mappers/streamAttributes.ts
- yarn.lock
Adds support for changing the frame background color after a stream has already been established. Prior to this change, it was only possible to change the frame background color when starting a stream or reconnecting to a stream.
As part of this work, the way the `background` property is set on the `<vertex-viewer>` containers has been changed to sync after frames are drawn, rather than having the value immediately reflected. This prevents the state where the background color of the container has changed, but we haven't received the updated image with the matching background color.
https://github.com/Vertexvis/vertex-web-sdk/assets/5252480/f074f55d-10df-4335-84b2-6977b4b495e8
- Verify that changing the `--viewer-background` and `--image-background` CSS properties updates the background …
> [PLAT-2348] Support changing frame background color for an active stream

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
We want to add phantom state as a feature of a SceneViewState that can be applied to the current scene individually, instead of applying the full SceneViewState.
Verify that a user can apply just the phantom state of a SceneViewState
None
Viewing snapshots
None
> [PLAT-3234] Apply phantom state of SceneViewState

- packages/viewer/src/components/viewer-view-cube/viewer-view-cube.spec.tsx
- packages/viewer/src/components/viewer-view-cube/viewer-view-cube.tsx
Previously, we always performed a 'view all' when selecting a standard view on the view cube, which caused exceptions when no geometry was visible.  Therefore, this PR adjusts the standard view interactions to only perform a 'view all' when geometry is visible.  If there's no visible geometry, the default camera position for the view will be used instead.
Verify view cube interactions work as expected, particularly when there's no visible geometry
None
Interacting with the view cube
None
> [PLAT-3187] Handle view cube interactions with no geometry

- packages/viewer/src/lib/stream/__tests__/stream.spec.ts
- packages/viewer/src/lib/stream/stream.ts
Updates the `ViewerStream` to always request images with at least 1x1 dimensions rather than requesting a zero-area image and displaying an error.
- Verify that errors are not logged when a frame is requested with zero-area dimensions
- For starting a stream and reconnecting, adding `display: none` to the viewer when initialized previously logged this error
- For updating stream dimensions, adding `display: none` to the viewer after it has loaded initially previously logged this
N/A
Stream dimensions
N/A
> [PLAT-3386] Always request images with at least 1x1 dimensions

- package.json
- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree-search/readme.md
- packages/viewer/src/components/scene-tree-search/scene-tree-search.spec.tsx
- packages/viewer/src/components/scene-tree-search/scene-tree-search.tsx
Updates the default behavior of the `<vertex-scene-tree-search>` element to require either an `Enter` press or a `blur` event to trigger the search by making the `debounce` field optional. If a `debounce` is specified, the search behavior will be the same as it was prior to this change.
- Verify default behavior of the search component
- Should search when `Enter` is pressed
- Should search when a `blur` event occurs (this also requires the value to have changed)
- Should always search when the input is cleared (either by button or by deleting all text)
- Verify debounce behavior of the search component continues to work as expected
N/A
scene-tree-search behavior
N/A
> [PLAT-3441] Update default scene-tree-search behavior

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/sceneViewStateLoader.spec.ts
- packages/viewer/src/lib/scenes/scene.ts
- packages/viewer/src/lib/scenes/sceneViewStateLoader.ts
- yarn.lock
Adds support for similar animation configuration as the `scene.camera().render()` method to the `scene.applySceneViewState()` and `scene.applyPartialSceneViewState()` methods. If this animation duration is configured, these methods will now perform a `flyTo` (and wait for the animation to complete) using the provided ID prior to applying the SceneViewState. The wait for the animation to complete is also configurable using the `waitForAnimation` flag, and if no animation duration is provided, it will maintain the same behavior as today. Additionally, the `scene.applyPartialSceneViewState()` method will only respect the provided animation if the `'camera'` feature is provided in the list of items to apply.
- Verify that the `scene.applySceneViewState()` without an animation configuration …
> [PLAT-3557] Add support for animation when loading SceneViewStates

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/scene-tree-table-layout/readme.md
- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.spec.tsx
- packages/viewer/src/components/scene-tree-table-layout/scene-tree-table-layout.tsx
Adds an event when the `<vertex-scene-tree-table-layout>`'s columns are resized.
This PR also fixes a couple issues around initialization of the layout with column widths don't match the full width of the layout. This fix will cause widths larger than the full width to be scaled down, and widths smaller than the full width to be scaled up.
- Verify a `columnsResized` event is emitted when the dividers are used to resize the columns
N/A
Column initial widths
N/A
> [PLAT-3624] Add column resize event for scene tree table

- packages/viewer/src/components/viewer/viewer.css
- packages/viewer/src/lib/interactions/__tests__/touchInteractionHandler.spec.ts
- packages/viewer/src/lib/interactions/touchInteractionHandler.ts
Adds an `event.preventDefault()` for touch events (similar to what we do for pointer events) and also adds a `user-select: none` to the viewer prevent accidental selection when rotating the model or interacting with the context menu.
- Verify that the viewer does not become selected when interacting on mobile
- Verify that default touch behavior (on iOS this magnifies what's under the tap point on long press) no longer occurs
N/A
Selection in viewer children (tested with markup and that allows selection similar to the behavior today)
N/A
> [PLAT-3729] Prevent viewer selection

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/components/viewer-hit-result-indicator/lib/__tests__/indicator.spec.ts
- packages/viewer/src/components/viewer-transform-widget/__tests__/widget.spec.ts
- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/stream/state.ts
- packages/viewer/src/lib/stream/stream.ts
- packages/viewer/src/lib/types/frame.ts
- yarn.lock
To avoid unnecessary CPU and network overhead, the depth buffer is not sent for successive temporal AA frames. This adds support for this; the SDK will reuse the previous depth buffer when possible.
[PLAT-3758](https://vertexvis.atlassian.net/browse/PLAT-3758)
[PLAT-3758]: https://vertexvis.atlassian.net/browse/PLAT-3758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLAT-3758: Temporal AA support

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-box-query-tool/readme.md
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.spec.tsx
- packages/viewer/src/components/viewer-box-query-tool/viewer-box-query-tool.tsx
- packages/viewer/src/lib/volume-intersection/index.ts
These changes enable developers to use the volume selection tool to get the controller when the controller is initialized or changes.
> [PLAT-3942] Exposing the volume selection model types and emitting the controller when changed

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/colorMaterial.ts
- packages/viewer/src/lib/scenes/mapper.ts
- yarn.lock
This PR updates the behavior when clearing a material override such that the part reverts to its default material instead of inheriting any material overrides applied to an ancestor of the item.
Verify material overrides work as expected. Specifically, verify the following use case:
1. Apply a material override to a parent item.
2. Clear the material override for one of the children.
3. Verify that the child now appears with its default material and the appearance of the remainder of the parts is unchanged.
Ability to set an override default material for a scene item
Material overrides
None
> [PLAT-3952] Clear material overrides

- packages/viewer/src/components/viewer-dom-element/utils.ts
- packages/viewer/src/components/viewer-dom-group/utils.ts
Prior to this check, we were not verifying that the matrix was set on the dom element. This check will verify that the matrix is also defined. The dom group was defined, but there was no matrix on it. This change prevents reading the matrix if the matrix is not present on the group or element.
Exception:
```
bundle.esm.js:675 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
at Object.multiply$2 [as multiply] (bundle.esm.js:675:17)
at getElementDepths (renderer2d.tsx:63:35)
at update2d (renderer2d.tsx:28:20)
at ViewerDomRenderer.updateElements (viewer-dom-renderer.tsx:158:9)
at ViewerDomRenderer.componentWillRender (viewer-dom-renderer.tsx:123:10)
at safeCall (index.js:1577:36)
at index.js:1353:39
at then (index.js:1586:61)
at dispatchHooks …
```
> [PLAT-3931] Verifying the dom element & dom group have a transform applied prior to acting on it

- packages/geometry/src/__tests__/quaternion.test.ts
- packages/geometry/src/__tests__/vector3.test.ts
- packages/geometry/src/quaternion.ts
- packages/geometry/src/vector3.ts
Adds an `eulerTo` utility for `Vector3`s to support determining the rotation to apply to the `<vertex-viewer-transform-widget>` based on a hit result normal and the global up vector.
- Verify that the behavior in Connect continues to work as expected (after it has been updated with this version)
- Unit tests
N/A
N/A
N/A
> [PLAT-1372] Add Vector3 Euler between method

- packages/viewer/src/components/viewer-measurement-distance/viewer-measurement-distance.tsx
Updates the `<vertex-viewer-measurement-distance>` component to dispose of its hover cursor when the mode changes from `edit` or `replace` to `''` to prevent an issue where the cursor would persist if the mode changed while hovering over geometry.
- Verify that changing the mode of the `<vertex-viewer-measurement-distance>` when the cursor is over geometry properly disposes of the cursor and returns it to the default
N/A
N/A
N/A
> [PLAT-4038] Dispose of measurement cursor when the mode is not replace or edit

- packages/viewer/package.json
- packages/viewer/src/components/scene-tree/lib/controller.ts
- yarn.lock
We now update the scene tree filter results immediately when visibility changes and the filter is set to remove hidden parts. Therefore, this PR listens for the current number of filter results and updates the state accordingly.
Verify scene tree filters work as expected, particularly when removing hidden parts
None
Scene tree filtering
https://github.com/Vertexvis/scene-tree-service/pull/202
> [PLAT-3897] Update filter results

- packages/viewer/package.json
- packages/viewer/src/lib/stream/__tests__/stream.spec.ts
- packages/viewer/src/lib/stream/stream.ts
- yarn.lock
Adds a deep equality check for the `streamAttributes` and `dimensions` of the stream. This prevents issues where equal but separate instances of an object would trigger an update and a new frame without any changes.
- Verify that providing new instances of an equal object for properties like `featureLines` does not result in an update and new frame
- Verify that providing new instances of a different object still does trigger an update and new frame
N/A
Stream attribute changes, resizing
N/A
> [PLAT-4084] Add deep equality check for stream attributes

- scripts/detect_release.sh
- scripts/publish_release.sh
Re-adds the tagging behavior on release along with the check on the `@vertexvis/viewer` package for detecting releases rather than the `@vertexvis/utils` package.
- Verify the next release correctly creates a Github tag and uses the `@vertexvis/viewer` package to detect releases
N/A
N/A
N/A
> [PLAT-4008] Re-add tagging and viewer package check

- README.md
- scripts/publish_release.sh
- scripts/release_notes.sh
Adds a `release_notes` script that will pull the `body` of the previous PR when a release is published, and generate release notes based on the contents of that PR. The generation of these release notes will attempt to read specifically the `Summary` section of the PR body, but will fall back to reading the full PR body up until the next heading (`##`) that is not the `Summary`. The script expects that the items to be included in the release notes are in a list format.
- Verify that releases are published with notes from the release PR
N/A
Releases
N/A
> [PLAT-3841] Automatic release note population

- packages/viewer/src/components/viewer-dom-group/viewer-dom-group.tsx
- packages/viewer/src/components/viewer-dom-renderer/renderer3d.tsx
- packages/viewer/src/components/viewer-dom-renderer/viewer-dom-renderer.tsx
- packages/viewer/src/components/viewer-view-cube/viewer-view-cube.css
Fixes an issue in WebKit based browsers where the view cube is flattened. This appears to happen because of a bug in WebKit with the `transform-style: preserve-3d` behavior not cascading through to `<slot>` children. Fix is to have the 3D renderers and elements not use shadow DOM and instead use scoped styles.
https://vertexvis.atlassian.net/browse/PLAT-4258
> [PLAT-4258] Fix view cube in WebKit browsers

- packages/viewer/src/components/viewer-dom-renderer/renderer2d.tsx
Fixes the positioning of 2D rendered elements inside a `<vertex-viewer-dom-renderer>` that was caused by scoping changes in #596.
https://vertexvis.atlassian.net/browse/PLAT-4258
> [PLAT-4258] Fix positioning of 2d rendered elements

- packages/viewer/src/components/viewer-dom-renderer/readme.md
- packages/viewer/src/components/viewer-dom-renderer/renderer2d.tsx
- packages/viewer/src/components/viewer-dom-renderer/renderer3d.tsx
- packages/viewer/src/components/viewer-dom-renderer/viewer-dom-renderer.spec.tsx
- packages/viewer/src/components/viewer-dom-renderer/viewer-dom-renderer.tsx
Previously, we required users to request depth buffers on every frame in order to use the occlusion and detachment features. This PR adds support for the feature when depth buffers are only requested on final frames.  
If depth buffers are requested for all frames, the occlusion and detached states will be updated on every frame. Conversely, if depth buffers are only requested on final frames, the occlusion and detached states will only be calculated
on final frames and will always report occluded and detached on transitional frames.
Verify occlusion and detachment features can be used both when depth buffers are requested on every frame and only on final frames
Support for only calculating occlusion and detachment on final frames 
Occlusion and Detachment
None
> [PLAT-4349] Support only calculating occlusion and detachment on final frames

- packages/viewer/src/lib/interactions/__tests__/interactionApiOrthographic.spec.ts
- packages/viewer/src/lib/interactions/flyToPositionKeyInteraction.ts
- packages/viewer/src/lib/interactions/interactionApiOrthographic.ts
- packages/viewer/src/lib/rendering/__tests__/vectors.spec.ts
- packages/viewer/src/lib/rendering/vectors.ts
- packages/viewer/src/lib/scenes/camera.ts
- packages/viewer/src/lib/types/frame.ts
We were not correctly updating the orthographic camera after the bounding box of a model changed, for example after a large transform. This PR correctly updates the camera to ensure subsequent interactions with the model behave as expected.
Verify orthographic cameras work as expected. Specifically, perform transforms that alter the model's bounding box and then interact with the model using rotation, panning, zooming, and fitting to specific parts.
Orthographic camera improvements
Interactions with orthographic cameras
None
> [PLAT-4360] Update orthographic camera after bounding box changes

- package.json
- packages/viewer/src/components/viewer-dom-renderer/renderer2d.tsx
- packages/viewer/src/components/viewer-dom-renderer/renderer3d.tsx
- packages/viewer/src/components/viewer-measurement-distance/__tests__/hitTest.spec.ts
- packages/viewer/src/components/viewer-measurement-distance/hitTest.ts
- packages/viewer/src/components/viewer-transform-widget/util.ts
- packages/viewer/src/lib/interactions/__tests__/interactionApiOrthographic.spec.ts
- packages/viewer/src/lib/interactions/interactionApiOrthographic.ts
- packages/viewer/src/lib/transforms/hits.ts
- packages/viewer/src/lib/types/__tests__/depthBuffer.spec.ts
- packages/viewer/src/lib/types/__tests__/viewport.spec.ts
- packages/viewer/src/lib/types/depthBuffer.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/lib/types/viewport.ts
This PR includes several improvements consolidate logic around camera calculations from individual methods for perspective and orthographic cameras into single methods.  This should reduce errors in the future where a user selected the incorrect method for their camera type.
Verify both perspective and orthographic cameras work as expected
Improvements to consolidate logic around camera calculations from individual methods for perspective and orthographic cameras into single methods. Specifically,
- Removes `viewport.transformPointToOrthographicRay` in favor of `viewport.transformPointToRay`
- Removes `viewport.transformPointToOrthographicWorldSpace` in favor of `viewport.transformPointToWorldSpace`
- Removes `depthBuffer.getLinearDepthAtPoint` and …
> [PLAT-4344] Consolidate camera calculations for perspective and orthographic cameras

- packages/viewer/src/lib/config.ts
- packages/viewer/src/lib/interactions/__tests__/mouseInteractions.spec.ts
- packages/viewer/src/lib/interactions/mouseInteractionHandler.ts
- packages/viewer/src/lib/interactions/mouseInteractions.ts
- packages/viewer/src/lib/interactions/pointerInteractionHandler.ts
- packages/viewer/src/lib/types/interactions.ts
These changes are to introduce a shorter delay in requesting a final frame on a ZoomInteraction. The 350ms was determined by performing a series of interactions from multiple internal users. Ultimately the feedback we received to make the change here is that the Zoom interaction felt slower. This should help a bit so that a final frame gets queued a little sooner.
The delay is not shortened further because the mouse `wheel` events could be invoked by the user in quick succession, which cause this zoom interaction to be "jerky" or "jumpy". This value of 350 appears to be high enough to avoid that, while still requesting the final frame quite a bit sooner. This value is also customizable if a consumer would like to override the default 350 in favor of a different debounce.
These changes …
> [PLAT-4504] Customizable Mouse Related Zoom Interactions

- packages/viewer/src/index.ts
- packages/viewer/src/lib/model-views/controller.ts
- packages/viewer/src/lib/model-views/index.ts
- packages/viewer/src/lib/model-views/mapper.ts
- packages/viewer/src/lib/model-views/types.ts
- packages/viewer/src/lib/types/index.ts
Reorganizes the types for model views to make exports easier to manage.
https://vertexvis.atlassian.net/browse/PLAT-4159
> [PLAT-4159] Export types for model views

- examples/align-two-surfaces/main.js
- examples/camera-manipulations/main.js
- examples/custom-interactions/main.js
- examples/loading-models/main.js
- examples/metadata-operations/main.js
- examples/work-instructions/instructions.js
- examples/work-instructions/main.js
- packages/geometry/README.md
- packages/geometry/README.template.md
- packages/viewer/README.template.md
- packages/viewer/readme.md
- packages/viewer/src/components/viewer-dom-renderer/readme.md
- packages/viewer/src/components/viewer-markup/readme.md
Modifies all of the cdn packages to use Js deliver instead of unpkg. I did do some smoke testing with these and these assets do appear to load a lot faster than unpkg.
> [PLAT-4506] Replacing unpkg with JSDelivr

- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/model-views/__tests__/controller.spec.ts
- packages/viewer/src/lib/model-views/controller.ts
- packages/viewer/src/testing/modelViews.ts
Updates the ModelViewController to support loading and unloading of ModelViews.
- Verify that calling `load` on the ModelViewController makes an UpdateSceneView gRPC request with both the current scene view ID and provided model view ID
- Verify that calling `unload` on the ModelViewController makes an UpdateSceneView gRPC request with the current scene view ID, then resets the scene view
N/A
N/A
N/A
> [PLAT-4149] Add support for loading and unloading ModelViews

- packages/viewer/src/lib/model-views/controller.ts
- packages/viewer/src/testing/modelViews.ts
Fixes a typo where the `load` and `unload` method of the ModelViewController were using `setModelViewId` rather than `setSceneViewId` to set the sceneViewId, resulting in an incorrect payload.
- Verify the `UpdateSceneViewRequest` payloads are correct
N/A
N/A
N/A
> [PLAT-4149] Fix setting of the sceneViewId in the ModelViewController

- packages/viewer/src/components/viewer-pin-group/pin-renderer.tsx
- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.css
- packages/viewer/src/components/viewer-pin-group/viewer-pin-group.tsx
- packages/viewer/src/lib/types/depthBuffer.ts
Detached pins and markers should be hidden from the viewer. This PR also updates the method to determine whether a point is detached to ensure that it returns the correct result.
Verify detached pins are hidden
Improvements to determining whether a point is detached
Determining whether a point is detached from geometry
None
> [PLAT-3943] Hide detached pins

- packages/viewer/src/lib/mappers/__tests__/frameStream.spec.ts
- packages/viewer/src/lib/mappers/corePbJs.ts
- packages/viewer/src/lib/mappers/frameStreaming.ts
- packages/viewer/src/lib/types/frame.ts
- packages/viewer/src/testing/fixtures.ts
- yarn.lock
Adds decoding of model view ID for the rendered frame. Clients can use this to know which model view is currently being rendered.
https://vertexvis.atlassian.net/browse/PLAT-4665
> [PLAT-4665] Add model view ID onto frame attributes

- packages/viewer/package.json
- packages/viewer/src/lib/model-views/__tests__/controller.spec.ts
- packages/viewer/src/lib/model-views/controller.ts
- packages/viewer/src/testing/modelViews.ts
- yarn.lock
Updates the model view controller to require a `sceneItemId` to be passed with the request to load a model view.
- Verify the payload is generated correctly for a `load` of a model view
- Verify the payload is generated correctly for an `unload` of a model view
N/A
N/A
N/A
> [PLAT-4674] Include Scene Item ID when loading a Model View

- packages/stream-api/src/streamApi.ts
- packages/stream-api/src/types.ts
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/lib/mappers/corePbJs.ts
- packages/viewer/src/lib/model-views/__tests__/controller.spec.ts
- packages/viewer/src/lib/model-views/controller.ts
- packages/viewer/src/lib/model-views/mapper.ts
- packages/viewer/src/lib/model-views/types.ts
- packages/viewer/src/testing/modelViews.ts
- yarn.lock
This changes the implementation for applying model views to use the new stream payload, instead of the gRPC-Web endpoint.
https://vertexvis.atlassian.net/browse/PLAT-4715
> [PLAT-4715] Apply model views using stream payload

- .github/workflows/branch.yml
- .github/workflows/master.yml
- .github/workflows/testing.yml
- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/interfaces.d.ts
- packages/viewer/src/lib/mappers/__tests__/streamAttributes.spec.ts
- packages/viewer/src/lib/mappers/streamAttributes.ts
- yarn.lock
This PR updates the scene compare feature to include the a stream key to compare to on the stream attributes as opposed to within the experimental rendering options.
Verify scenes can be compared by including a stream key in the comparison information in the stream attributes
None
Comparing scenes
None
> [PLAT-4743] Include scene comparison information in stream attributes

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/interfaces.d.ts
- packages/viewer/src/lib/mappers/__tests__/streamAttributes.spec.ts
- packages/viewer/src/lib/mappers/streamAttributes.ts
- yarn.lock
We only want to allow users to initiate a scene comparison by providing the stream key. Therefore, this PR removes support for including a scene id to compare to the existing scene.
Verify version compare works as expected when providing a stream key
None
Version compare
None
> [PLAT-4743] Remove ability to compare by scene id

- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.spec.tsx
- packages/viewer/src/components/scene-tree-table-cell/scene-tree-table-cell.tsx
- packages/viewer/src/components/scene-tree-table-cell/utils.ts
Adds a `this.hostEl.blur()` when handling `pointerup` events for scene-tree actions (toggle expansion, isolate, toggle visibility). Because we call `preventDefault` on the `pointerup` event, this was causing the `document.activeElement` to remain as the `<vertex-scene-tree-table-cell>` element, rather than returning focus to the `<body>` element. Because of this, key presses would result in a focus outline appearing on the last pressed action button, which this PR corrects.
As a side-note, the above behavior can be tested by setting a `pointerup` breakpoint in Chrome, and checking the value of `document.activeElement` before and after the event handlers have run.
- Click a scene-tree action button
- Without focusing another element, press a number or letter key
- Verify that no blue focus …
> [PLAT-1780] Blur scene-tree-table-cell elements on action pointerup

- packages/viewer/src/lib/pmi/mapper.ts
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
This PR fixes a bug that was incorrectly converting PMI annotations ids to UUID2l.
Verify a user can operate on individual PMI annotations
None
Operating on PMI annotations
None
> [PLAT-5083] Correctly convert pmi annotation id

- packages/viewer/src/components/scene-tree-table-resize-divider/scene-tree-table-resize-divider.css
- packages/viewer/src/components/scene-tree-table-resize-divider/scene-tree-table-resize-divider.tsx
This PR updates the scene tree table resize divider to appear a lighter gray by default and show the full blue divider on both hover and drag.
Verify the scene tree table resize divider appears as expected
None
Appearance of scene tree table resize divider
None
> [PLAT-5550] Update scene tree table resize divider

- packages/stream-api/package.json
- packages/viewer/package.json
- packages/viewer/src/lib/scenes/__tests__/mapper.spec.ts
- packages/viewer/src/lib/scenes/mapper.ts
- packages/viewer/src/lib/scenes/scene.ts
- yarn.lock
Adds support for passing `shading` as an element when performing a partial apply of a scene view state. When passed, this value will apply the `noDefaultLights` value present in a scene view state.
- Verify that passing `shading` when partially applying a scene view state properly applies the shading
Added support for partially applying the shading saved in a scene view state
N/A
https://github.com/Vertexvis/frame-streaming-service/pull/450
> [PLAT-5573] Partial apply SVS shading support

- packages/stream-api/package.json
Updates the semver range of the `@vertexvis/utils` peer dependency within the `@vertexvis/stream-api` package to allow for anything above or equal to the latest release. Prior to this change, it was not possible to pin the version and remove NPM warnings, as the version included in the `@vertexvis/viewer` dependencies was generally higher than `^0.20.3`, but almost never within a patch version range. This would result in warnings related to the peer dependency not matching, requiring a specific installation of `"@vertexvis/utils": 0.20.3` to resolve the warning, which didn't line up with the latest version of the `@vertexvis/viewer` package being installed.
This change should allow for latest release versions of `@vertexvis/viewer` to install without warnings (as it installs the latest …
> [PLAT-4005] Update utils package peer dependency

- packages/html-templates/package.json
- packages/stream-api/package.json
- packages/utils/package.json
- packages/utils/src/objects.ts
- packages/viewer/package.json
- yarn.lock
Follow up from #649 to fix a couple other dependency related issues:
* The `protobufjs` peer dependency range for `@vertexvis/stream-api` has been updated to `<8.0.0`
* The viewer already installs `7.2.4`, which it has been compatible with for some time
* The `@types/classnames` dependency has been removed as it is deprecated and unnecessary
* The `long` package has been added as a viewer dependency
* This was previously being pulled in by an outdated version of `protobufjs`, and required for parsing the `Long` metadata type
* The `lodash.isequal` dependency has been removed in favor of `fast-deep-equal` as it was deprecated
- Once released, verify the package.json dependencies specified in [PLAT-6059](https://vertexvis.atlassian.net/jira/software/c/projects/PLAT/boards/112?selectedIssue=P …
> [PLAT-6059] Dependency warning fixes

- packages/stream-api/package.json
- packages/utils/src/mapper.ts
- packages/viewer/package.json
- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer-transform-widget/readme.md
- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/components/viewer/viewer.spec.tsx
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/interfaces.d.ts
- packages/viewer/src/lib/interactions/__tests__/interactionApi.spec.ts
- packages/viewer/src/lib/interactions/__tests__/interactionApiOrthographic.spec.ts
- packages/viewer/src/lib/mappers/camera.ts
- packages/viewer/src/lib/mappers/index.ts
- packages/viewer/src/lib/scenes/__tests__/scene.spec.ts
- packages/viewer/src/lib/scenes/__tests__/sceneViewStateLoader.spec.ts
- packages/viewer/src/lib/scenes/camera.ts
- packages/viewer/src/lib/scenes/scene.ts
- packages/viewer/src/lib/scenes/sceneViewStateLoader.ts
- packages/viewer/src/lib/stream/stream.ts
- packages/viewer/src/lib/types/__tests__/loadableResource.spec.ts
- packages/viewer/src/lib/types/loadableResource.ts
- yarn.lock
This PR adds support for optionally including a camera type override when starting a stream, applying a scene view, or resetting a scene. When the camera type override is included, the desired camera will be converted to the desired type before being applied to the scene.
Verify a user can include a camera type override when starting a stream, applying a scene view, or resetting a scene 
Ability to include a camera type override when starting a stream, applying a scene view, or resetting a scene
Loading and resetting views
Changes in FSS and SS
> [PLAT-5800] Support camera type overrides

- packages/viewer/src/components.d.ts
- packages/viewer/src/components/viewer/readme.md
- packages/viewer/src/components/viewer/viewer.tsx
- packages/viewer/src/index.ts
- packages/viewer/src/lib/types/orientation.ts
This PR adds the ability to reload the scene from the viewer element. The method disconnects the stream and then immediately reconnects the same scene.
Further, this PR also exports the 'Orientation' type.
Verify a viewer element can reload its scene
Ability to reload the scene from the viewer element
None
None
> [PLAT-5521] Support reloading scene from viewer element

- packages/viewer/stencil.config.ts
This PR enables the `experimentalImportInjection` flag in our StencilJS configuration. This flag creates dynamic imports for all of the lazy-loaded components, such that they can be properly included with certain bundling tools, such as Vite. See https://stenciljs.com/docs/config-extras#experimentalimportinjection for more information on the flag (also note that we're using `experimentalImportInjection` instead of `enableImportInjection` due to the version of Stencil we're using).
One additional detail included with the `experimentalImportInjection` flag is that it has potential side-effects for the size of our bundles, so as part of this work, some analysis of those changes was done using [rollup-plugin-analyzer](https://www.npmjs.com/package/rollup-plugin-analyzer), and the top-level …
> [PLAT-6842] Enable experimental import injection flag

- packages/viewer/src/components/scene-tree/scene-tree.spec.tsx
- packages/viewer/src/components/scene-tree/scene-tree.tsx
This PR improves ancestor selection behavior. Specifically, now when a user has clicked a part enough times to select the entire tree, when they click the part again, the selection will be cleared and only the part will be selected. The process of selecting the part's ancestors can then be repeated if desired. 
1. Click an item in the scene tree until the entire tree is selected
2. Click the item again. Note that the selection is cleared and only the part is selected now
Improved ancestor selection
Selection
None
> [PLAT-7164] Improve ancestor selection
